// ==UserScript==
// @name         Toyo-igo-Tygem-JP-English-UI
// @namespace    http://tampermonkey.net/
// @version      5.5
// @description  Patches lang.xml, G_VAR server names, and game record CateName fields
// @author       Bexico
// @match        *://www.toyo-igo.com/*
// @match        *://toyo-igo.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==

(function () {
  'use strict';

  const T = {
    'BT_OK':'OK','BT_OK2':'OK','BT_CANCEL':'Cancel','BT_SAVE2':'Save',
    'BT_YES':'Yes','BT_NO':'No','BT_CLOSE':'Close','BT_EXIT':'Exit',
    'BT_RELOGIN':'Reconnect','BT_LOGIN':'Log in','BT_GUESTMODE':'Log in as Guest',
    'BT_MAXIMIZE':'Maximise','BT_RESTORE':'Back',
    'BTN_REQUEST':'Apply','BTN_REQUEST2':'Change request',
    'BTN_REJECT':'Decline','BTN_ACCEPT':'Accept',
    'BTN_REJECT_S':'Decline','BTN_ACCEPT_S':'Accept',
    'BTN_INVITE_SEARCH':'Search','BTN_ON_S':'On','BTN_OFF_S':'Off',
    'LB_LINE19':'19×19','LB_LINE9':'9×9','LB_LINE13':'13×13',
    'AINORMAL_LINE19':'AI 19×19',
    'MENUBAR_LOBBY':'Lobby','MENUBAR_OPEN':'My games',
    'MENUBAR_NOTIFY':'Notifications','MENUBAR_EVENT':'Events',
    'MENUBAR_SETUP':'Settings','MENUBAR_HELP':'Help',
    'MENUBAR_EXIT':'Leave','MENUBAR_LOGOUT':'Disconnect',
    'LOBBYBTN_LOGOUT':'Disconnect','LOBBYBTN_SERVER':'Change server',
    'LOBBYBTN_CHAT':'Chat','LOBBYBTN_SHOP':'Shop',
    'LOBBYBTN_SEARCH':'Search','LOBBYBTN_GAME':'Request game',
    'LOBBYBTN_MENU':'Menu','LOBBYBTN_AUTOMATCH':'Auto-match (19×19)',
    'LOBBYBTN_AUTOMATCH9':'Auto-match (9×9)','LOBBYBTN_AIMATCH':'Play AI',
    'LOBBYBTN_MAKEROOM':'Create room',
    'LB_ALL':'All','LB_RIVAL':'Same','LB_JAPAN':'Japan',
    'LB_GOODMAN':'Friends','LB_BADMAN':'Blocked',
    'TAB_ALL':'All','TAB_BET':'Wager','TAB_NORMAL':'Game',
    'TAB_EQUAL':'Same rank','TAB_RELAY':'Relay','TAB_UPPER':'Higher rank',
    'TAB_LOWER':'Lower rank','TAB_PRO':'Pro (P)','TAB_BAD':'Block list',
    'TAB_GOOD':'Friends','TAB_MATSU':'Same rank',
    'LB_SERVER':'Server','LB_SEARCHID':'Search ID',
    'LB_USERLIST':'Waiting players','LB_LOGIN':'Log in',
    'LB_FAVORITE':'☆ Favourites','LB_WANTLOGIN':'Please log in',
    'LB_WANTJOIN':'Register free','LB_FREEMEMBER':'Free member',
    'LB_PAYMEMBER':'Paid member','LB_GREET':'Title','LB_TALKINPUT':'Chat',
    'ST_JOINMEMBER':'Register free',
    'LB_GAME':'Game','LB_WATCH':'Spectate','LB_WAIT':'Waiting',
    'LB_OFFICIAL':'Ranked','LB_FRIENDLY':'Friendly',
    'LB_GAMEOFFICIAL':'Game – Ranked','LB_GAMEFRIENDLY':'Game – Friendly',
    'LB_LECTURE':'Lecture','LB_RELAY':'Relay','LB_OPMATCH':'Commentary',
    'LB_ONGAME':'In game','LB_REJGAME':'Declined','LB_ONVIEW':'Spectating',
    'LB_ONLOBBY':'In lobby','LB_WIN':'Win','LB_LOSE':'Loss',
    'ROOM_NO':'No.','ROOM_KIND':'Type','ROOM_USER':'Players',
    'ROOM_WHITE':'White','ROOM_AI':'AI win%','ROOM_BLACK':'Black',
    'ROOM_STATUS':'Status','ROOM_GREET':'Title','USER_NAME':'Waiting',
    'USER_GRADE':'Rank','USER_WIN':'Win','USER_LOSE':'Loss',
    'USER_MANNER':'Manner','USER_GAME':'Game','USER_POS':'Location',
    'ST_ROOMLIST':'Game room list','ST_USERLIST':'Waiting players',
    'ST_CHATLIST':'Lounge chat',
    'SETUP_H_UTIL':'Settings','SETUP_GAME_INVITE':'19×19 invitation',
    'SETUP_GAME_INVITE9':'9×9 invitation','SETUP_ROOM_INVITE':'Room invitation',
    'SETUP_TALK11':'1:1 chat','SETUP_ALARM':'Alarm sound',
    'SETUP_MEMO':'On message received','SETUP_MEMO_0':'Show message',
    'SETUP_MEMO_1':'Save to inbox','SETUP_STONE_SOUND':'Move sound',
    'SETUP_STONE_SOUND_0':'All on','SETUP_STONE_SOUND_1':'Current room only',
    'SETUP_STONE_SOUND_2':'All off','SETUP_NOTIFY_FRIEND':'Friend login alarm',
    'SETUP_NOTIFY_CIRCLE':'Club login alarm',
    'SETUP_H_BOARD':'Board','SETUP_S_BOARD':'Stones',
    'SETUP_UTIL':'Features','SETUP_GAME19_OK':'Accept 19×19 requests',
    'SETUP_GAME9_OK':'Accept 9×9 requests',
    'SETUP_INVITE_OK':'Accept room invitations',
    'SETUP_TALK11_OK':'Accept 1:1 chat','SETUP_NOTIFY':'Notifications',
    'SETUP_NOTIFY_SND_ON':'Alarm sound on',
    'SETUP_F_LOGIN_SND_ON':'Friend login alarm on',
    'SETUP_G_LOGIN_SND_ON':'Club login alarm on',
    'SETUP_SOUND':'Sound','SETUP_STONE_SND':'Move sound',
    'SETUP_STONE_SND_ALL':'All on','SETUP_STONE_SND_CUR':'Current room only',
    'SETUP_STONE_SND_OFF':'All off','SETUP_BOARD':'Board',
    'FMT_PRO':'P{0} dan','FMT_DAN':'{0} dan','FMT_GEUB':'{0} kyu',
    'ST_PLAYING':'In game','ST_VIEWING':'Spectating','ST_UID':'ID',
    'ST_CRANK':'Rank','ST_MBSHIP':'Membership','ST_TPOINT':'Go Points',
    'TITLE_MATCH':'Game request','TITLE_FMATCH':'Friendly game',
    'TITLE_OMATCH':'Ranked game',
    'GAMEBTN_EXIT':'Leave','GAMEBTN_EXIT_R':'Leave','GAMEBTN_SNS':'Share',
    'GAMEBTN_REVIEW':'Review','GAMEBTN_ANALYZE':'Analysis',
    'GAMEBTN_MENU':'Menu','GAMEBTN_ORDER':'Move list',
    'MENU_JOIN':'Enter room','MENU_REQ':'Request game','MENU_INVITE':'Invite',
    'MENU_BOKGI':'Review','MENU_BACK':'Undo request','MENU_SKIP':'Pass',
    'MENU_GEGA':'Score','MENU_EQUAL':'Draw request',
    'MENU_DS_CONFIRM':'Confirm dead stones','MENU_DS_CANCEL':'Cancel dead stones',
    'MENU_DS_RETRY':'Re-mark dead stones','MENU_GIVEUP':'Resign',
    'MENU_REFRESH':'Return to game','MENU_GUMTO':'Start review',
    'MENU_REGUMTO':'Reset','MENU_AUTO':'Replay','MENU_STOP':'Stop',
    'MENU_CLOSE':'Close','MENU_BOK_MENU':'Review menu',
    'MENU_BOK_CASTER':'Select master','MENU_BOK_REVIEW':'Start review',
    'MENU_BOK_REVIEW2':'Reset','MENU_BOK_REVIEW_END':'Back',
    'MENU_BOK_END':'End review','MENU_SAVE':'Save',
    'MENU_COPYNAME':'Copy text','MENU_MATCH_REQ':'Request game',
    'MENU_MATCH_F':'Friendly request','MENU_USERINFO':'Member info',
    'MENU_USERFIND':'Find location','MENU_USERGIBO':'Member games',
    'MENU_USERTALK':'1:1 chat','MENU_USERMEMO':'Send message',
    'MENU_ADDGOOD':'Add friend','MENU_DELGOOD':'Remove friend',
    'MENU_ADDBAD':'Block','MENU_DELBAD':'Unblock',
    'MENU_MYINFO':'My profile','MENU_MEMO':'Messages',
    'MENU_HELP':'Help','MENU_SETUP':'Settings','MENU_SUSUN':'Move list',
    'MENU_RECOMM':'Best move','MENU_SHOWCOORD':'Show coordinates',
    'MENU_AICOACH':'AI coaching','MENU_JOINUSER':'Player list',
    'MENU_ANALYZE':'Analyse','MENU_ANALYZE2':'Win rate analysis',
    'MENU_TERRI':'Estimate','MENU_REVIEW':'Review',
    'MENU_COORD':'Coordinates','MENU_PRINT':'Print','MENU_SHARED':'Share',
    'MENU_OPENGIBO':'Game list','MENU_SHOWUSER':'Player list',
    'MENU_SHOWEXP':'Commentary list','MENU_DAYNIGHT':'Light/Dark mode',
    'MENU_FULLMODE':'Maximise/Restore','MENU_MATCH':'Find opponent',
    'MENU_MATCH19':'19×19 game','MENU_MATCH9':'9×9 game',
    'MENU_AIMATCH':'AI game','MENU_AIMATCH19':'19×19 AI',
    'MENU_AIMATCH9':'9×9 AI','MENU_VIEWGIBO':'Game replay',
    'MENU_MAKEROOM':'Create room','MENU_MORE':'More','MENU_GREET':'Phrases',
    'MENU_AIJUDGE':'AI judgement','MENU_NEW_AUTOMATCH':'Auto-match',
    'MENU_NEW_AUTOMATCH_9':'9×9',
    'RMMENU_ANALYZE':'Game\nanalysis','RMMENU_PRINT':'Print',
    'RMMENU_SHOWCOORD':'Show coordinates','RMMENU_HIDECOORD':'Hide coordinates',
    'RMMENU_SHARED':'Share','RMMENU_INVITE':'Invite',
    'RMENU_HOME':'Home','RMENU_GIBO':'Game replay','RMENU_AIZEN':'AI Go',
    'RMENU_SHOP':'Shop','RMENU_CHARGE':'Free charge',
    'RMENU_SETUP':'Settings','RMENU_EDITOR':'Game editor','RMENU_CIRCLE':'Club',
    'LB_PHASE0':'Preparing','LB_PHASE1':'Opening','LB_PHASE2':'Middle game',
    'LB_PHASE3':'End game','LB_PHASE4':'Scoring',
    'LB_PHASE5':'Finished','LB_PHASE6':'Abandoned',
    'ST_ROOMPHASE_READY':'Waiting','ST_ROOMPHASE_CHOBAN':'Opening',
    'ST_ROOMPHASE_JUNGBAN':'Middle game','ST_ROOMPHASE_ZONGBAN':'End game',
    'ST_ROOMPHASE_END':'Finished','ST_ROOMPHASE_STOP':'Abandoned',
    'ST_ROOMPHASE_BOKGI':'Review','ST_ROOMPHASE_ONAIR':'Live',
    'LB_TIMESET':'Time settings','LB_TMHIGH':'Blitz','LB_TMNORMAL':'Normal',
    'LB_TMLOW':'Long','LB_TMTIME':'Main time','LB_TMSEC':'Byo-yomi',
    'LB_TMSEC_EX':'Extra time','LB_TMCNT':'Byo-yomi periods',
    'LB_TMTYPE_H':'Hour','LB_TMTYPE_M':'Min',
    'LB_TMTYPE_ZERO':'None','LB_TMTYPE_UNLIMIT':'Unlimited',
    'LB_MATCHCOND':'Game conditions','LB_PMGAME':'Ranked game',
    'LB_FRGAME':'Friendly game','LB_RULESET':'Basic settings',
    'LB_DUM':'Komi (Black)','LB_NODUM':'None','LB_GAMERULE':'Rule',
    'LB_RULE0':'Even','LB_RULE1':'Fixed colour',
    'LB_DOLSEL':'Choose colour','LB_DOLWHITE':'White','LB_DOLBLACK':'Black',
    'LB_DOLAUTO':'Auto','LB_SETBACK':'Undo allowed','LB_SETBACK2':'No undo',
    'LB_GAMEYES':'Available','LB_GAMENO':'Unavailable',
    'WINCODE-2':'No result','WINCODE-1':'Void','WINCODE0':'Draw',
    'WINCODE1':'Black wins','WINCODE2':'White wins',
    'WINCODE3':'Black wins by resignation','WINCODE4':'White wins by resignation',
    'WINCODE5':'Black wins on time','WINCODE6':'White wins on time',
    'WINCODE7':'Black wins (disconnect)','WINCODE8':'White wins (disconnect)',
    'WIN_GVUP':'Win by resignation','WIN_TIME':'Win on time',
    'WIN_DIS':'Win by disconnect','LOSE_GVUP':'Loss by resignation',
    'LOSE_TIME':'Loss on time','LOSE_DIS':'Loss by disconnect','DRAW':'Draw',
    'EVETN_SUPERMATCH':'Pro Super Match',
    'AI_ZEN7':'ZEN7','AI_LEELA':'Leela','AI_KATAGO':'KataGo',
    'AI_OTHER':'AI Go','AI_BEGIN':'Beginner AI','AI_SET':'AI settings',
    'COM_LEVEL':'CPU level','BT_GOGAME':'Play',
    'TITLE_POSTBOX':'Messages','BT_SELALL':'Select all',
    'BT_MEMOWRITE':'New message','BT_SELDEL':'Delete selected',
    'BT_MEMOCLEAR':'Delete all','MEMOLIST_SENDER':'Sender',
    'MEMOLIST_DATE':'Date','MEMOLIST_SUBJECT':'Subject',
    'MEMOTAB_ADMIN':'Staff inbox','MEMOTAB_SYSTEM':'System inbox',
    'MEMOTAB_GENERAL':'General inbox','ST_SENDER':'Sender',
    'ST_RECEIVER':'To','ST_SUBJECT':'Subject','ST_CONTENT':'Message',
    'BTN_SEND':'Send','BTN_REPLY':'Reply','BTN_REPORT':'Report',
    'NOTIFY_MEMO':'Messages','NOTIFY_EVENT':'Events','NOTIFY_GAME':'Games',
    'NOTIFY_SYSTEM':'System','NOTIFY_NOTICE':'Notices',
    'CONF_LOGOUT':'Disconnect?','PROGRAM_KEY':'Toyo-igo',
    'BTN_EXITSERVER':'Disconnect','BTN_LOBBYHELP':'Help centre',
    'BTN_MEMO':'Messages','BTN_ADMIN':'Staff','BTN_LOGOUT':'Log out',
    'BT_MAKEROOM':'Create','BT_INVITE':'Invite','BT_REGAME':'Rematch',
    'ROOM_NO':'No.','ST_GRADE':'Rank','ST_ID':'ID','ST_PWD':'Password',
    'ST_LOGIN':'Log in','ST_SAVEPWD':'Save password','ST_FIND':'Search',
    'ST_SELSVR':'Select server','MSG_COPY':'Text copied.','ST_MENU':'Menu',
    'BTN_MY_PAGE':'My page','ALARM_MSG':'Notice',
    'FMT_COUNTUSER':'{0} users','LB_NEWOPEN':'New','ST_TOBE':'Coming soon',
    'MENU_MYCIRCLE':'Club','MENU_CIRCLECHAT':'Club chat',
    'MENU_CIRCLEHOME':'Club home',
    'ROOMKIND_RELAY':'Tournament relay','ROOMKIND_BIG':'9-dan game',
    'ROOMKIND_NORMAL':'Standard','ROOMKIND_LIVE':'Tournament/Commentary',
    'BT_ROOMTYPE1':'Standard game room','BT_ROOMTYPE2':'Voice review/commentary',
    'BT_ROOMTYPE3':'Live relay','BT_ROOMTYPE4':'Commentary relay',
    'ST_POINT':'Points','ST_GAIN':'Gained','ST_LOSS':'Lost','ST_SUM':'Total',
    'UST_INFO_BASIC':'Basic info','UST_USERID':'Member ID','UST_CURRANK':'Rank',
    'UST_MEMBERSHIP':'Status','UST_INFO_GAME':'19×19 game info',
    'UST_RES_CUR':'Current record','UST_RES_ALL':'All-time record',
    'UST_RES_UP':'Ranked record','UST_RES_FR':'Friendly record',
    'FIND_USER':'Member search',
    'TASK_LOBBY':'Lobby','TASK_AIGAME':'AI game','TASK_VIEWGIBO':'Game replay',
    'WINRATIO_W':'White win%','WINRATIO_B':'Black win%',
    'EVAL_LEVEL1':'Perfect','EVAL_LEVEL2':'Good','EVAL_LEVEL3':'Average',
    'EVAL_LEVEL4':'Weak','EVAL_LEVEL5':'Mistake','EVAL_LEVEL6':'Blunder',
    'HELLO_GROUP1':'General','HELLO_GROUP2':'Greetings','HELLO_GROUP3':'Farewells',
    'HELLO_GROUP4':'Thanks','HELLO_GROUP5':'Encouragement','HELLO_GROUP6':'Help',
    'HELLO_GROUP7':'Gratitude','HELLO_GROUP8':'Praise','HELLO_GROUP9':'Apology',
    'HELLO_GROUP10':'Staff',
    'ERR_IDCONFLICT':'ID already connected.',
    'ERR_WRONG_ID_PASSWORD':'Incorrect ID or password.',
    'ERR_SERVERCHECK':'Cannot log in to this server.',
    'ERR_USERLIMITOVER':'Server is full.',
    'ERR_PENALTYUSER':'Your account is restricted.',
    'ERR_NOTFEEUSER':'Paid members only.',
    'ERR_UNKNOWN':'An unknown error occurred.',

    // Blue membership buttons
    'ST_JOINMEMBER':'Register free',
    'LB_WANTJOIN':'Register free',
    'LB_FREEMEMBER':'Free member',
    'LB_PAYMEMBER':'Paid member',
    'LIVEFREE_LEVEL':'Free member',
    'LIVEACADEMY_LEVEL':'Paid member',
    'LIVELEADERSCLUB_LEVEL':'Paid member',
    'LIVEPLUS_LEVEL':'Paid member',
    'LIVELIGHT_LEVEL':'Paid member',
    'BTN_OFFER_MEMBERSHIP':'Upgrade',
    'LB_MS_TEMPTATION_JOIN':'Upgrade',
    'LB_MS_TEMPTATION_EXTEND':'Extend',

    // Win/loss labels (additional)
    'LB_BLACK_WIN':'Black wins','LB_WHITE_WIN':'White wins',
    'LB_BLACK_WIN_P':'Black wins by {0}','LB_WHITE_WIN_P':'White wins by {0}',
    'GT_WIN':'%d W','GT_LOSE':'%d L',
    'FMT_WINLOSE':'{0}W {1}L',
    'BWIN_FMT':'Black {0} wins','WWWIN_FMT':'White {0} wins',
    'WIN_FMT':'{0} wins','LOSE_FMT':'{0} losses',
    'WINTYPE0':'Black wins','WINTYPE1':'White wins',
    'WINTYPE_0':'Black %s wins','WINTYPE_1':'White %s wins',
    'WINTYPE_2':'Draw','WINTYPE_3':'Black wins by resign',
    'WINTYPE_4':'White wins by resign','WINTYPE_5':'Black wins (disconnect)',
    'WINTYPE_6':'White wins (disconnect)','WINTYPE_7':'Black wins on time',
    'WINTYPE_8':'White wins on time','WINTYPE_9':'Void',
    'WINTYPE_10':'White wins by judgement','WINTYPE_11':'Black wins by judgement',
    'WINTYPE2_0':'%s losses','WINTYPE2_1':'%s wins',
    'WINTYPE2_2':'Draw','WINTYPE2_3':'Loss by resign',
    'WINTYPE2_4':'Win by resign','WINTYPE2_5':'Loss (disconnect)',
    'WINTYPE2_6':'Win (disconnect)','WINTYPE2_7':'Loss on time',
    'WINTYPE2_8':'Win on time',
    'WINTYPE_3S':'Black wins by forfeit','WINTYPE_4S':'White wins by forfeit',
    'FMT_RESULT':'{0} wins by {1}','FMT_RESULT_BAN':'{0} wins by {1}.5',
    'FMT_RESULT_SURRENDER':'{0} wins by resign',
    'FMT_RESULT_DISCONNECT':'{0} wins (disconnect)',
    'FMT_RESULT_TIME':'{0} wins on time',
    'FMT_RESULT_JUDGE':'{0} wins by AI judgement',
    'FMT_RESULT_DRAW':'Jigo (draw)',
    'FMT_RESULT_CANCEL':'Void',

    // Nav tabs (game modes)
    'BBSGIBO_OMOK':'Gomoku','BBSGIBO_SCORE':'Score','BBSGIBO_LINE9':'9×9',
    'MENU_NEW_AUTOMATCH_OMOK':'Gomoku',
    'MENU_NEW_AUTOMATCH_OMOK_RENJU':'Gomoku (Renju)',
    'MENU_NEW_AUTOMATCH_SCORE':'Score Go',
    'MENU_MATCH_OMOK':'Gomoku request',
    'MENU_MATCH_OMOK_RENJU':'Gomoku (Renju) request',
    'MENU_MATCH_SCORE':'Score Go request',
    'MENU_OMOK_REQ':'Gomoku request (friendly)',
    'MENU_OMOK_REQ_RENJU':'Gomoku Renju (friendly)',
    'MENU_SCORE_REQ':'Score Go (friendly)',

    // Player/room counts
    'FMT_COUNTUSER':'{0} users','FMT_USERCNT':'{0} users',
    'FMT_LROOM':'%5d rooms  %5d players',
    'FMT_LUSER':'%5d players',
    'ST_JOINUSER':'Players','ROOM_USER':'Players',
    'FMT_USER_NAME':'Players ({0})',
    'ST_PCNT':'Players',

    // Rank progression
    'LS_1UPGEUK':'+1 kyu: +%d wins needed',
    'LS_2UPGEUK':'+2 kyu: +%d wins needed',
    'LS_1UPDAN':'+1 dan: +%d wins needed',
    'LS_2UPDAN':'+2 dan: +%d wins needed',
    'LS_1DNGEUK':'-1 kyu: -%d losses',
    'LS_2DNGEUK':'-2 kyu: -%d losses',
    'LS_1DNDAN':'-1 dan: -%d losses',
    'LS_2DNDAN':'-2 dan: -%d losses',

    // AI win rate
    'DLGTITLE_AIWINRATE':'AI win rate analysis',
    'FMT_AIWINRATE':'Win rate analysis: {0}',
    'LB_GIBO_ANALYZE':'Win rate analysis',

    // Participation / membership warnings
    'WARN_MEMBER':'Paid members only.',
    'ERROR_PAYMEMBER':'Paid members only.',
    'PAY_WARNING':'Paid members only.',
    'TS_NOT_FREE0':'Paid members only.',
    'WARN_POSOKLEVEL':'Paid members only.',
    'ERR_MEMBERONLYPROXY':'Paid members and 9-dan only.',
    'ERR_LIMITMOVESVR':'Paid members only.',
    'WARN_GTP_NOT_MEMBER':'AI KataGo (PRO) is for paid members.\nPaid members get unlimited games.',
    'WARN_COUNTOVER_ANALYZE':'Free members: 1 use per day.\nRegister as paid member for unlimited use.',
    'WARN_COUNTOVER_CREATE_ROOM':'Free members: 1 use per day.\nRegister as paid member for unlimited use.',
    'WARN_MY_GIBO':'Game replay is for paid members only.',
    'WARN_NO_AVAIL_FOR_PREVIEW':'Free members cannot use win rate analysis during review.',
    'DS_WARN_MEMBER_TERITORY':'Position analysis after move 100\nis for paid members only.',
    'WARN_USED_FOR_A_DAY2':'Daily limit reached.\nRegister as paid member for unlimited use.',
    'WARN_TPOINT_FOR_GA':'Free members need {0} points for win rate analysis.',
    'MSG_JOIN_FOR_GA':'※ Register as paid member for free win rate analysis.',
    'NMSG_KATAGO_INFO':'※ Register as paid member for unlimited KataGo games!\n\nGames are saved after 11 moves.\nNo time limit.',

    // Score Go / Gomoku descriptions
    'EXP_OMOK_LIMIT':'Gomoku matches players within a similar rating range.\nRenju rules (no double-3, double-4, or overline for Black).\n1 min + 20 sec byo-yomi (3 periods). Auto colour selection.\n\nRequest a game?',
    'EXP_SCORE_LIMIT':'Score Go matches players within a similar rating range.\nStarts from a position of 20–50 moves in.\nOpponent HP decreases with each bad move.\nWinner decided when HP reaches 0 or after 150 moves.\n\nRequest a game?',

    // Misc remaining
    'TT_SHOWUSER':'Player list',
    'WARN_GAMEREQ_NONE':'Select an opponent from the player list.',
    'WARN_GAMEREQ_REJ':'This player cannot accept games. Please choose another.',
    'ST_CHEVENTBETLIMIT':'New Year wager limit',
    'ZENCERT_WIN':'Congratulations on your win!',
    'MSG_SCORE_START':'Proceeding to score map.',
    'MATCH_ERR_CREATE_ROOM':'Failed to create room.',
    'MATCH_ERR_JOIN_ROOM':'Failed to join room.',
    'MATCH_ERR_MAX_ROOM':'Already in too many rooms.',
    'WARN_DUPLICATE_LIVE':'Already in a live relay room.',
    'WARN_HELP_LIMIT_OMOK':'Judgement requests are not available in Gomoku.',
    'WARN_HELP_LIMIT_SCORE':'Judgement requests are not available in Score Go.\nPlay to move 150 or reduce opponent HP to 0.',

    'CONTEST_STEP0':'None','CONTEST_STEP1':'Qualifying',
    'CONTEST_STEP2':'Round of 64','CONTEST_STEP3':'Round of 32',
    'CONTEST_STEP4':'Round of 16','CONTEST_STEP5':'Quarter-finals',
    'CONTEST_STEP6':'Semi-finals','CONTEST_STEP7':'Final',

    'HG_10':'Hello. Nice to meet you.',
    'HG_11':'Please treat me kindly.',
    'HG_12':'I hope we have a fun game...',
    'HG_13':'That was fun.',
    'HG_14':'Thank you. Let\'s play again.',
    'HG_20':'Nice to meet you.',
    'HG_21':'Please treat me kindly.',
    'HG_22':'I\'m glad to meet you.',
    'HG_23':'The weather is nice today.',
    'HG_24':'It\'s been a while.',
    'HG_30':'That was fun.',
    'HG_31':'Would you like another game?',
    'HG_32':'Enjoy the rest.',
    'HG_33':'Let\'s meet again.',
    'HG_34':'Goodbye.',
    'HG_40':'Please treat me kindly.',
    'HG_41':'I\'ll do my best.',
    'HG_42':'I won thanks to good luck.',
    'HG_43':'Thanks to you, I had a good time.',
    'HG_44':'Enjoy the rest.',
    'HG_50':'Good luck!',
    'HG_51':'I didn\'t see that move!',
    'HG_52':'Thank you for letting me watch a heated match.',
    'HG_53':'Thank you for the game. I learned a lot.',
    'HG_54':'That\'s okay. Do your best next time!',
    'HG_60':'Please click on the dead stones.',
    'HG_61':'I want to return to game mode.',
    'HG_62':'There\'s a problem with the scoring.',
    'HG_63':'I\'m stuck and can\'t make a move.',
    'HG_64':'This player is being malicious, I\'m in trouble.',
    'HG_70':'Thank you very much.',
    'HG_71':'I learned a lot thanks to you.',
    'HG_72':'That was a great game to watch.',
    'HG_73':'Thank you for the pleasant music.',
    'HG_74':'Thank you for the enjoyable lecture.',
    'HG_80':'You\'re very skilled.',
    'HG_81':'You\'re very strong.',
    'HG_82':'You have very good manners.',
    'HG_83':'Well played.',
    'HG_84':'Wonderful.',
    'HG_90':'Sorry.',
    'HG_91':'I\'ll be away from my seat for a moment.',
    'HG_92':'I don\'t have time; let\'s play another time.',
    'HG_93':'Something urgent came up, I must leave.',
    'HG_94':'Sorry, my connection dropped.',
    'HG_200':'Hello. Is there a problem?',
    'HG_201':'There are no more moves; please start scoring.',
    'HG_202':'In scoring, please click on your own dead stones.',
    'HG_203':'Please mind your manners, or you may be banned.',
    'HG_204':'The game isn\'t over yet.',
    'HG_205':'After scoring, if you don\'t agree, we\'ll return to the game.',
    'HG_206':'If you intentionally refuse scoring, staff will decide the result.',
    'HG_207':'Your opponent\'s connection dropped. Please wait a moment.',
    'HG_208':'Please observe chat manners.',
    'HG_209':'Thank you. Please continue to enjoy.',


    // ===== Newly translated keys (1087 entries) =====
    'ADULT_KEYWORD0':'Wager',
    'ADULT_KEYWORD1':'Bet',
    'ADULT_KEYWORD2':'Wager',
    'ADULT_KEYWORD3':'Wager',
    'ADULT_KEYWORD4':'Genius',
    'AI_CGI':'CGI',
    'AI_NORMAL9':'General AI',
    'AI_ZEN7_7':'ZEN7 (3 kyu – 7 dan)',
    'AI_ZEN7_9':'ZEN7 (8 dan – 9 dan)',
    'AIBEGINER_LINE9':'AI 9×9',
    'ALARM_CIRCLE':'Club notification',
    'ALARM_FRIEND':'Friend notification',
    'AM_END':'No member accepted the game request. Please wait and try again.',
    'AM_NEXT_STEP':'No members currently requesting with the same conditions. Requesting automatically under "Negotiate time" mode.',
    'AMSETUP_NO_QUESTION':'Keep these settings until next login',
    'AMSETUP_SEL_01':'5 min / 20 sec (3 periods)',
    'AMSETUP_SEL_02':'10 min / 30 sec (3 periods)',
    'AMSETUP_SEL_03':'Negotiate time',
    'AMSETUP_START':'Request',
    'AMSETUP_TITLE':'Game condition setup',
    'AMSETUP9_SEL_01':'None / 20 sec (3 periods)',
    'AMSETUP9_SEL_02':'5 min / 20 sec (3 periods)',
    'AMSETUP9_SEL_03':'Negotiate time',
    'BANK_ST0':'Deposit bank',
    'BANK_ST1':'Depositor',
    'BANK_ST2':'Deposit',
    'BANK_ST2_1':'Won',
    'BANK_ST3':'Purchased item',
    'BANK_ST4':'Gift recipient',
    'BANK_ST4_1':'(Only for gifts)',
    'BETBAR_BET':'Wager',
    'BETBAR_CHEER':'Cheer',
    'BETBAR_INFO':'Info',
    'BETCHEER_FIRECRACKER':'Firework cheer',
    'BETCHEER_INFO':'Cheer details / settings',
    'BETCHEER_TYPE1':'1 rose cheer',
    'BETCHEER_TYPE10':'10 rose cheers',
    'BETCHEER_TYPE30':'30 rose cheers',
    'BETCHEER_TYPE5':'5 rose cheers',
    'BETCHEER_TYPE60':'60 rose cheers',
    'BETCHEER_TYPE90':'90 rose cheers',
    'BETINFO_ALL':'Full wager details',
    'BETINFO_GAMER':'Player info',
    'BETINFO_SHEET':'#Wager information#',
    'BETTAB_PERIODX_ROSE':'Section %d cheer details',
    'BETTAB_PERIODX_ROSE1':'Cheer details',
    'BIGMATCHNOTE_START':'A Big Match: {1} vs {2} has started in Room #{0}.',
    'BS_ERR_BET':'A wager error occurred. Please try again.',
    'BS_ERR_FIXED_ITEM_LIMIT':'Fixed items can only be used once per section.',
    'BS_ERR_LACK_MONEY':'Insufficient cyber points. Please wager within your available limit.',
    'BS_ERR_MAX_LIMIT_OVER':'Maximum wager amount exceeded.',
    'BS_ERR_SAME_IP':'Wagering is not allowed from the same IP as a player.',
    'BS_SECTION_END':'Wagering has ended. Thank you for your support.',
    'BS_SECTION_START_OTHER':'[{0} section] Wager is now open.',
    'BT_ALLLEVEL':'Public room',
    'BT_BETLIMIT':'Wager limit',
    'BT_CANCELREQ':'Cancel request',
    'BT_CASTOPTION1':'No camera',
    'BT_CASTOPTION2':'Lecture only (8 kbps)',
    'BT_CHANGE':'Select',
    'BT_CHARGE':'Charge',
    'BT_CHARGE_TPOINT':'Charge points',
    'BT_CHARGECASH':'Charge Cash',
    'BT_CROSS_M':'Cross-play',
    'BT_DELRIGHT':'Revoke master /',
    'BT_ENTERHISTORY':'View room history',
    'BT_EXPCMT':'Save to commentary list (Mobile relay)',
    'BT_EXPLAIN_OWNCOUNTRY':'Own country only',
    'BT_GIBO':'Game record',
    'BT_GOURL':'Go',
    'BT_NOTICE_REG':'Post announcement',
    'BT_OK_PAY':'Use points',
    'BT_ONEVENT':'Event match',
    'BT_PASS_R':'Grant master',
    'BT_PAYRANGE':'Charge scope',
    'BT_PAYRULE':'Paid',
    'BT_RANGEALL':'All',
    'BT_RANGEOWN':'Own country',
    'BT_REG':'Register',
    'BT_ROOMTYPE5':'Red envelope wager room',
    'BT_SECRET':'Set password',
    'BT_SELECT':'Select',
    'BT_SETCASTER':'Grant master',
    'BT_SETTRYTURN':'Grant cross-play',
    'BT_UPDOWN_GUIDE':'Rating system',
    'BT_USERMENU':'Member menu',
    'BT_VISIONRANGE':'Public scope',
    'BTN_AIJUDGE':'Request AI judgement',
    'BTN_CANCELBET':'Cancel',
    'BTN_CHKCONFIRM':'Confirm selection',
    'BTN_CLOSEREFER':'Close reference',
    'BTN_DOBET':'Place wager',
    'BTN_FIND':'Search',
    'BTN_FIND_LOCAL_GIBO':'Open file',
    'BTN_FINDGIBO':'Game record search',
    'BTN_GOSHOP':'Shop',
    'BTN_GOSVR':'Go to server',
    'BTN_JOINSEL':'Join selected',
    'BTN_MAXBET':'Max',
    'BTN_MYGIBO':'My records',
    'BTN_PRESS_STONE':'Place stone',
    'BTN_PROGIBO':'Pro records',
    'BTN_READ':'Read',
    'BTN_REJ_INVITE':'Decline game invites (19×19)',
    'BTN_REJ_INVITE9':'Decline game invites (9×9)',
    'BTN_SOUND_OFF':'Sound OFF',
    'BTN_SOUND_ON':'Sound ON',
    'BTN_URLCOPY':'Copy URL',
    'BTN_URLMAKE':'Generate URL',
    'BTN_USERGIBO':'Member records',
    'BTN_VIEWGRAPH':'Show graph',
    'CALL_CONFIRM':'Reason: {0}. Call staff?',
    'CALL_CONFIRM1':'Call staff?',
    'CALL_ST1':'If no staff are available, the following message will be delivered to staff. (200 characters max)',
    'CALL_ST2':'1:1 help provides consultation via 1:1 chat.',
    'CALL_ST3':'If 1:1 chat acceptance is not checked, consultation is unavailable. Please enable it in Settings. Available hours: 10 AM – 5 PM (excluding weekends and holidays).',
    'CALL_ST4':'Email support',
    'CALL_ST5':'Contact: support@toyo-igo.com',
    'CALL_TIMEWARNING':'You can call staff once every 20 seconds.',
    'CASH_OWN':'Cash held',
    'CASH_REMAIN':'Remaining cash',
    'CASH_SUBTRACT':'Cash used',
    'CAST_GAMEROOM':'Room %04d – %s vs %s',
    'CAST_GAMEROOM_EX':'{0} – {1} vs {2}',
    'CAST_READYROOM':'Room %04d – %s preparing',
    'CAST_READYROOM_EX':'{0} – {1} preparing',
    'CB_CIRCLE':'Club members',
    'CB_FRIEND':'Friends list',
    'CB_RECENTLY':'Recent senders',
    'CB_RECENTLY_R':'Recent recipients',
    'CHANGESVR_ANALYZER':'Invite AI',
    'CHAT_INPUT':'Chat',
    'CHEER_FIRECRACKER':'Firework',
    'CHEER_ROSE':'Rose',
    'CHK_BETTING':'Allow wagers',
    'CHK_BETTING_SECTION':'Section wagers',
    'CHK_BETTING_SECTION2':'Disable section wagers',
    'CHK_BETTING2':'No wagers',
    'CHK_BLOCKUSER':'Decline messages from the above member',
    'CHK_FISCHER':'Fischer time',
    'CHK_FISCHER2':'No Fischer time',
    'CHK_NOCHEER':'Hide firework cheers',
    'CHK_NOSHOW':'Hide rose cheers',
    'CHK_NOSOUND':'Mute firework cheer sound',
    'CHK_TERRITORY':'Enable position analysis',
    'CHK_TERRITORY2':'Disable position analysis',
    'CHR_BOMB':'Firework cheer',
    'CHR_BOMB_CNT':'%d shots',
    'CHR_BONUS':'Bonus',
    'CHR_MYROSE':'My rose cheers',
    'CHR_NOTICE1':'*Rose prize winners receive bonus points.',
    'CHR_ROSE':'Rose cheer',
    'CHR_TOTALROSE':'Total rose cheers',
    'CHR_WIN_PRIZE':'Rose prize winner',
    'CLOG_USER_LOGIN':'%.3d %.2d %.2d **[[[ TEST_USERLOGIN',
    'CS_CHEERFAIL_1':'Cheer for {1} in room #{0} failed: exceeded maximum cheer count.',
    'CS_CHEERFAIL_2':'Cheer for {1} in room #{0} failed: insufficient points.',
    'CS_CHEERFAIL_3':'Cheer for {1} in room #{0} failed.',
    'DLG_NOTICEREG_NATION':'Country',
    'DLG_REALNAME_WATCH_BTN':'Spectate',
    'DLGTITLE_AMSETUP':'Game Condition Setup',
    'DLGTITLE_BETINFO':'Wager Details',
    'DLGTITLE_BETTING':'Place Wager',
    'DLGTITLE_BPLAYINFO':'Player Wager Info',
    'DLGTITLE_CHANGECAST':'Select Relay Room',
    'DLGTITLE_MAKEROOM':'Create Room',
    'DLGTITLE_REFER':'Reference Diagram',
    'DLGTITLE_ROSE':'Cheer Details',
    'DLGTITLE_SELCASTER':'Select Presenter',
    'DLGTITLE_SELUSER':'Select Master',
    'DLGTITLE_SNSBOX':'Share via SNS',
    'EMEMO_CNT_OVER':'Daily message limit exceeded. Upgrade to paid membership for unlimited use.',
    'EMEMO_FULL_TARGET':'"{0}"\'s message box is full; the message could not be sent.',
    'EMEMO_ID_NOEXIST':'"{0}" is not a valid ID.',
    'EMEMO_NATIONDIFF':'Messages cannot be sent to members from other countries.',
    'ERR_BANUSER':'You are restricted from entering this server.',
    'ERR_GOSVR_BROKEN':'Connection to the server (9×9) has been terminated.',
    'ERR_GOSVR_BROKEN_RETRY':'Connection to the server (9×9) has been terminated. Reconnect?',
    'ERR_GOSVR_FAILCONN':'The request could not be handled.',
    'ERR_GOSVR_GAME':'The game was voided due to a server issue. (reason: {0})',
    'ERR_MY_USERNUMBER':'Failed to retrieve member information. The game records menu cannot be used.',
    'ERR_NOTFOUNDPRELOGIN':'A login problem occurred while using a proxy server.',
    'ERR_NOTOVER18':'This server is restricted to users 18 and older.',
    'ERR_OPERATOR_IPCHECK':'Your account has been permanently suspended.',
    'ERR_RANKSERVER':'Only members of the appropriate rank can connect to this server.',
    'ERR_SHUTDOWN_NOTOVER16':'Access is restricted under the minor protection law.',
    'ERR_SYSTEM_FAILURE':'A system error occurred and the content cannot be viewed.',
    'ERROR_CREATEROOM':'Failed to create the room.',
    'ERROR_GUEST_NOT_ALLOW':'This feature is unavailable when logged in as Guest. Log in (register as a member)?',
    'ERROR_JOINROOM':'Error joining room #%d.',
    'ERROR_JOINROOM0':'This lecture is exclusively for students of the revolutionary voice lecture series. For inquiries contact %s.',
    'ERROR_JOINROOM1':'This room is for Leaders Club members only.',
    'ERROR_JOINROOM2':'This room is for paid members only.',
    'ERROR_JOINROOM3':'Free members are restricted from entering when spectating exceeds %d people.',
    'ERROR_JOINROOM4':'Room #%d is a paid room. %d T-points will be deducted. Continue?',
    'ERROR_JOINROOM5':'Room #%d is a paid room. Insufficient T-points to enter.',
    'ERROR_JOINROOM6':'This room is for Winners Club members only.',
    'ERROR_JOINROOM7':'This room is for paid members only.',
    'ERROR_JOINROOM8':'This room is for Plus members only.',
    'ERROR_NOFIND':'No search results found.',
    'EVAL_MSG':'Game analysis in progress. Please wait.',
    'EVETN_BETMISSION_AI':'AI vs 9-dan Big Match',
    'EVETN_BETMISSION_DEF':'9-dan Big Match',
    'EVETN_BETMISSION_PRO_SUPER':'Pro Super Match',
    'EXIT_ANALYZER':'Remove AI',
    'EXP_9LINE_COND':'1 min / 20 sec (3 periods)',
    'EXP_9LINE_LIMIT':'9×9 matches players within a similar rating range using 1 min + 20 sec byo-yomi (3 periods), even game (auto nigiri). Request a game?',
    'FAVORITE_EXP':'Press a key to add to favourites.',
    'FMT_AI_BEGIN':'Beginner – AI {0}',
    'FMT_AI_KATAGO':'KataGo AI – {0}',
    'FMT_AI_ZEN':'ZEN7 – AI {0}',
    'FMT_CHAT11_REJ':'"{0}" declined your 1:1 chat request.',
    'FMT_CHAT11_REJ2':'"{0}" has 1:1 chat set to decline.',
    'FMT_CHAT11_YESNO':'"{0}" requests 1:1 chat.',
    'FMT_CONN_SVR':'Connected to "{0}" server.',
    'FMT_COPYNAME':'Copied "{0}"',
    'FMT_DUM':'{0} Points',
    'FMT_EQUAL_ERROR':'A draw error occurred. ({0})',
    'FMT_EQUAL_ERROR_NO':'Draw requests are not available currently.',
    'FMT_EQUAL_ERROR_OVER':'Draw requests are limited to 4 total.',
    'FMT_EQUAL_REQ':'"{0}" requests a draw.',
    'FMT_ERRORAILOGIN':'AI login error. (code %d)',
    'FMT_EXPROOM':'Commentary Room #{0}',
    'FMT_FEE_9LINE':'(Fee: {0} {1}%)',
    'FMT_GAMEROOM':'Game Room #{0}',
    'FMT_GEGA_ERROR':'An error occurred during scoring. ({0})',
    'FMT_GONGJE':'Black {0} ½-Point advantage',
    'FMT_GONGJE2':'Black {0} advantage',
    'FMT_GTP_ERROR':'AI Go %s is not responding. Try again later.',
    'FMT_GTP_FULL':'No available AI Go %s. Try again later.',
    'FMT_GTP_FULL2':'Connection to %s server is unstable; game ended.',
    'FMT_GTP_NOCASH':'1,000 Cash required to play against AI %s. Cash can be purchased in the shop.',
    'FMT_GTP_NOITEM':'No item available to play against AI %s. Items can be purchased in the shop.',
    'FMT_GTP_SKIP':'AI Go %s passed; switching to scoring mode.',
    'FMT_GTP_SURRENDER':'AI Go %s resigned.',
    'FMT_HELPMSG':'\\?[{0}]☎110{{1}} User "{2}" in Room #{1} requested help. ({3})',
    'FMT_HIDDEN_ODD_EVENT':'*******************',
    'FMT_HIDDEN_ODD_RESULT1':'-----------------------------',
    'FMT_HIDDEN_ODD_RESULT2':'******************************',
    'FMT_HIDDEN_ODD_START':'******************************',
    'FMT_INFONAME':'Info for "{0}"',
    'FMT_INVITE_OK':'Invite message sent to "{0}".',
    'FMT_ITEM_EVENT':'(E) {0}',
    'FMT_ITEM_REWARD':'(R) {0}',
    'FMT_LINE':'%×%',
    'FMT_LIVECAST':'Room #{0} relay',
    'FMT_NEGI_GET':'{0}0,000 points earned',
    'FMT_NEGI_LOSE':'{0}0,000 points lost',
    'FMT_NEGI_MONEY':'{0}0,000-point wager',
    'FMT_NOTFOUND_ID':'"{0}" is not a member.',
    'FMT_PLAYER_BET_LIMIT':'Players cannot place wagers after move {0}.',
    'FMT_PLAYER_DISCONNECT':'{0} has disconnected.',
    'FMT_POSDELAY':'Move delay {0} sec',
    'FMT_RATIO':'{0}×',
    'FMT_RELAY':'Relay – #{0}',
    'FMT_REMOTEROOM':'{0} – Room #{1}',
    'FMT_RESULT_SCORE':'{0}: {1} points (captures: {2})',
    'FMT_ROOMNO':'Room #{0}',
    'FMT_RP_LINE9':'{0} RP',
    'FMT_RULE':'Handicap {0} stones',
    'FMT_SCORE_CHOICE':'{0}: Select {1}',
    'FMT_SCORE_CHOICE_MSG':'Both players chose {0}; automatic colour selection will determine sides.',
    'FMT_SECCNT':'{0} sec / {1} periods',
    'FMT_SECCNT2':'{0} sec / {1} periods',
    'FMT_SVRCHG':'Move to [{0}] server?',
    'FMT_SVRCHG_ERR_CONN':'Cannot communicate with [{0}] server.',
    'FMT_TALK11_REJ':'{0} declined the 1:1 chat.',
    'FMT_TIME_HM':'%d h %02d min',
    'FMT_TIMEINFO':'{0} sec / {1} periods / {2} captures',
    'FMT_TIMEMIN':'{0} min',
    'FMT_USERGIBO':'Game records of {0}',
    'FMT_WITHDRAW_ERROR':'An undo request error occurred. ({0})',
    'FMT_WITHDRAW_REQ':'"{0}" requests an undo.',
    'G_STRLAY0':'1',
    'G_STRLAY1':'2',
    'G_STRLAY2':'3',
    'G_STRLAY3':'4',
    'G_STRLAY4':'5',
    'G_STRLAY5':'6',
    'G_STRLAY6':'7',
    'G_STRLAY7':'8',
    'G_STRLAY8':'9',
    'G_STRPOSUK0':'Joseki',
    'G_STRPOSUK1':'Variation',
    'G_STRPOSUK2':'Fuseki',
    'G_STRPOSUK3':'Bad move',
    'GAME_CERTIFY_GRADE':'Rank certification game',
    'GAME_REQUEST': '%s (%s – %dW %dL) requests a game. Accept?',
    'GAME_REQUEST_LINE9':'{0} requests a friendly 9×9 game. Accept?',
    'GAME_REQUEST_OMOK':'{0} requests a friendly Gomoku game. Accept?',
    'GAME_REQUEST_OMOK_RENJU':'{0} requests a friendly Gomoku (Renju) game. Accept?',
    'GAME_REQUEST_PART1': '"%s" (%s – %dW %dL) requests a game.',
    'GAME_REQUEST_PART2':'Time negotiation',
    'GAME_REQUEST_PART3':'Accept the game request?',
    'GAME_REQUEST_SCORE':'{0} requests a friendly Score Go game. Accept?',
    'GAME_REQUEST2':'%s (%s) requests a game. Accept?',
    'GAME_REQUEST3':'%s (%s – %d RP) requests a game. Accept?',
    'GAME_REQUEST9_PART1':'"%s" (%dW %dL) RP %s requests a game.',
    'GM_REQUESTGAME_R':'Request a game with {0}?',
    'GM_RESERVEDGAME':'This is a tournament game room. Please observe game and spectating etiquette.',
    'GM_RESPONSEGAME_R0':'{0} has requested to start the game.',
    'GM_RESPONSEGAME_R1':'Start the game?',
    'GM_RETURNMATCH_REQ':'Request a rematch with {0}? Black/White will swap automatically. Game conditions will be the same as the previous game.',
    'GM_RETURNMATCH_REQEX':'Request a rematch with {0}? Game conditions will be the same as the previous game.',
    'GM_RETURNMATCH_RSP':'Rematch requested with {0}. Waiting for {1} to accept.',
    'GT_EQUAL':'%d D',
    'GT_GAMEKIND0':'Ranked game',
    'GT_GAMEKIND1':'Friendly game',
    'GT_GAMEKIND10':'Ranked game – Section wager',
    'GT_GAMEKIND11':'Friendly game – Section wager',
    'GT_GAMEKIND2':'Ranked game – Wager',
    'GT_GAMEKIND3':'Life & death',
    'GT_GAMEKIND4':'Life & death – Wager',
    'GT_GAMEKIND5':'Friendly game – Wager',
    'GT_GONGJE':'Black 6½-Point advantage',
    'GT_OPT4':'Game requests are automatically declined during AI games.',
    'GT_POS':'#{0}',
    'GT_RES_BET':'%dW %8dL  Win%d %s',
    'GT_RULE0':'Even',
    'GT_RULE1':'Fixed colour',
    'GT_RULE2':'2-stone handicap',
    'GT_RULE3':'3-stone handicap',
    'GT_RULE4':'4-stone handicap',
    'GT_RULE5':'5-stone handicap',
    'GT_RULE6':'6-stone handicap',
    'GT_RULE7':'7-stone handicap',
    'GT_RULE8':'8-stone handicap',
    'GT_RULE9':'9-stone handicap',
    'GT_SCORE_TIME_ADD':'Extra time',
    'GT_TOTAL':'%d T',
    'GTAB_DEAD':'Life & death',
    'GTAB_FRIEND':'Friendly game',
    'GTAB_UPDOWN':'Ranked game',
    'GTYPE_AI':'AI',
    'GTYPE_EXPLAIN':'Commentary',
    'GTYPE_LIVE':'Lecture',
    'GTYPE_MYOSU':'Tsumego',
    'GTYPE_NORMAL':'Standard',
    'GTYPE_VIEWGIBO':'Replay',
    'GWARN_NOGAMEINFO':'No pre-set game conditions exist. Please contact staff.',
    'GWARN_NOPARTNER':'The opponent has not entered the room yet. Please wait.',
    'HELP_CASE0':'My opponent is deliberately refusing to score.',
    'HELP_CASE1':'My opponent won\'t play.',
    'HELP_CASE2':'My opponent\'s clock is not counting down.',
    'HELP_CASE3':'The scoring result is wrong.',
    'HELP_CASE4':'What should I do in this situation?',
    'HELP_CONFIRM':'Room #{0} – Reason: {1}. Call for help in the waiting room?',
    'HELP_ROOMNO':'Room #{0}',
    'HELP_ST0':'Please select (or enter) the room number where help is needed.',
    'HELP_ST1':'Select request type',
    'HELP_ST3':'Room number',
    'HELP_WARNING1':'Please select (or enter) the room to call for help.',
    'HELP_WARNING2':'Please select a help message!',
    'HELP_WARNING3':'The specified room number does not exist!',
    'HELP_WARNING4':'Free members can request help once per minute.',
    'HOUSE_FMT1':'{0} Points',
    'HOUSE_FMT2':'{0}½ Points',
    'HOUSE_HALF':'½ Point',
    'IDS_BLACK_TERI':'Black leads by %d (excluding komi)',
    'IDS_BLACK_TERI_DETAIL':'Black {0} advantage',
    'IDS_DRAW_TERI':'Draw',
    'IDS_DRAW_TERI_DETAIL':'Draw',
    'IDS_DX_TALKEXIT':'{0} left the chat.',
    'IDS_DX_TALKON':'1:1 chat connected with {0}.',
    'IDS_HALTGAME_Q':'There is a suspended game in Room #{0}. Rejoin?',
    'IDS_MOVE_ROOM':'A tournament game has been opened for you in Room #{0}. Would you like to move there?',
    'IDS_SCORE_TERI_DETAIL':'Black {0} (Score) {1} White',
    'IDS_WHITE_TERI':'White leads by %d (excluding komi)',
    'IDS_WHITE_TERI_DETAIL':'White {0} advantage',
    'IDS_XX_11TALK_Q':'{0} has requested a 1:1 chat. Accept?',
    'IDS_XXX_INVITE_Q':'{0} ({1}) has invited you to Room #{2}. Accept?',
    'IDS_XXXXX_INVITE_Q':'{0} ({1} – {2}W {3}L) has invited you to Room #{4}. Accept?',
    'INPUT_CONTESTGAME':'Enter tournament or pro name',
    'INPUT_IDNICK':'Enter ID or nickname',
    'ITEM_DOUBLE':'Double',
    'ITEM_EVENT':'Event',
    'ITEM_FIXED':'Fixed',
    'ITEM_GAME':'Game',
    'ITEM_INSURE':'Insurance',
    'ITEM_REWARD':'Reward',
    'ITEM_TIP_DOUBLE':'Bonus points paid on successful predictions (max wager: {0} points). Two consecutive wins with the same item trigger extra bonuses! Insurance items can be used together; fixed-odds items cannot be combined.',
    'ITEM_TIP_FIXED':'On a losing prediction, 50%–100% of your stake is randomly refunded (max wager: {0} points). Can be used together with Double and Fixed items!',
    'ITEM_TIP_INSURE':'On a losing prediction, 50%–100% of your stake is randomly refunded (max wager: {0} points). Can be used together with Double and Fixed items!',
    'KEY_CALLHELP_119':'☎119',
    'LB_ADDNODE':'Insert node',
    'LB_BLACK':'Black',
    'LB_CNTTYPE_FMT':'{0} times',
    'LB_DELNODE':'Delete node',
    'LB_DELREFER':'Remove recommendation',
    'LB_FROMTEXT':'Paste SGF text',
    'LB_GAMETYPE':'Game type',
    'LB_GAMETYPE0':'Normal',
    'LB_GAMETYPE1':'Fischer',
    'LB_GAMETYPE2':'Timeout',
    'LB_GIBO_CREATE':'Create variation / ref diagram',
    'LB_GIBSEARCH':'Game search',
    'LB_GUESTMODE':'Log in as Guest',
    'LB_LEFT_RECENT':'(Newest on left)',
    'LB_LINKOPEN':'Open link',
    'LB_NEGI_BY':'{0} points',
    'LB_NONEGI':'No wager',
    'LB_OUTTEXT':'Export SGF text',
    'LB_POINT':'Point Go',
    'LB_POPUP':'Pop-up window',
    'LB_REALTIME_REFE_CREATE':'AI commentary',
    'LB_REFER':'Recommended move',
    'LB_SECTYPE_FMT':'{0} sec',
    'LB_TIER_0':'Bronze',
    'LB_TIER_1':'Silver',
    'LB_TIER_2':'Gold',
    'LB_TIER_3':'Platinum',
    'LB_TIER_4':'Emerald',
    'LB_TOCLIPBOARD':'Copy to clipboard',
    'LB_WHITE':'White',
    'LIVE_OPERATOR':'Staff',
    'LIVECOACH_LEVEL':'Amateur teacher',
    'LIVEMASTER_LEVEL':'Master',
    'LIVEPRO_LEVEL':'Pro teacher',
    'LIVESPECIAL_LEVEL':'Special',
    'LIVEVOD_LEVEL':'Auto-recording',
    'LIVEVVIP_LEVEL':'VVIP',
    'LIVEWINNERS_LEVEL':'VIP member',
    'LOGIN_DATE':'%dY/%dm/%d %dH:%dM',
    'LS_AUTOGEGA':'Auto scoring',
    'LS_AUTOGEGA_NOTOK':'%s declined the auto scoring request.',
    'LS_AUTOGEGA_NOTOK_M':'Auto scoring request declined.',
    'LS_AUTOGEGA_NOTOK_REASON':'(There are still playable moves remaining.)',
    'LS_AUTOGEGA_OK':'%s accepted the auto scoring request.',
    'LS_AUTOGEGA_OK_M':'Auto scoring request accepted.',
    'LS_AUTOGEGA_Q':'%s has requested scoring. Click Accept to see results.',
    'LS_AUTOGEGA_REQ':'Scoring has been requested to %s.',
    'LS_AUTOGEGA_REQ2':'%s has requested scoring. Click Accept to see results.',
    'LS_AUTOGEGA_RESULTAGREE':'%s agreed with the auto scoring result.',
    'LS_AUTOGEGA_RESULTDISAGREE':'%s disagreed with the auto scoring result.',
    'LS_AUTOGEGA_START':'Starting automatic scoring.',
    'LS_BAN0':'half',
    'LS_CROSS_EXP':'Cross-play is available in "try-move" mode only.',
    'LS_DELALLFRIEND':'Really remove the entire friends list?',
    'LS_DRAWGAME':'%s lost.',
    'LS_EQUAL_CANCEL':'Draw request cancelled.',
    'LS_EQUAL_NOTOK':'%s declined the draw request.',
    'LS_EQUAL_OK1':'%s accepted the draw request.',
    'LS_EQUAL_OK2':'%s and %s have agreed to a draw.',
    'LS_EQUAL_Q':'%s requested a draw. Accept?',
    'LS_EQUAL_REQ':'Request a draw?',
    'LS_EQUAL_REQ2':'%s requested a draw with %s.',
    'LS_EQUAL_SURRENDER':'A draw request cannot be made more than %d times. Further draw requests will be treated as a resignation. Resign?',
    'LS_ERRORSILVER':'An AI Go error occurred.',
    'LS_EXPIRE9DAN':'Until 9-dan status is maintained',
    'LS_EXPIREDAY':'Until %dY/%dm/%d',
    'LS_EXPLAIN_NOTICE':'★ Tournament Announcement ★',
    'LS_EXPLAINTITLE':'[ Commentary for move %d ]',
    'LS_GAME_RULE':'Per Toyo-igo rules and player agreement, this result is final.',
    'LS_GEGA_CANCEL':'Scoring request cancelled. ({0})',
    'LS_GEGA_CANCEL_TIME':'Scoring was cancelled due to timeout.',
    'LS_GEGA_DEAD_C':'%s has finished marking dead stones.',
    'LS_GEGA_DEAD_M':'Dead stone marking completed.',
    'LS_GEGA_DEAD_R':'%s cancelled the dead stone confirmation. Please re-mark.',
    'LS_GEGA_DEAD_R0':'Dead stone confirmation cancelled. Re-marking.',
    'LS_GEGA_DEAD_W':'Dead stone marking completed. Please wait for {0} to finish marking.',
    'LS_GEGA_NOTOK':'%s declined the scoring request.',
    'LS_GEGA_NOTOK_ALL':'Both players rejected the scoring result.',
    'LS_GEGA_NOTOK_B':'Black rejected the scoring result.',
    'LS_GEGA_NOTOK_M':'Scoring request declined.',
    'LS_GEGA_NOTOK_W':'White rejected the scoring result.',
    'LS_GEGA_OK':'%s accepted the scoring request.',
    'LS_GEGA_OK_M':'Scoring request accepted.',
    'LS_GEGA_Q':'%s has requested scoring. Remove dead stones?',
    'LS_GEGA_Q2':'{0} has requested scoring. Accept?',
    'LS_GEGA_REQ':'Scoring has been requested to %s.',
    'LS_GEGA_REQ2':'%s has requested scoring.',
    'LS_GEGA_START':'Starting scoring. Please mark dead stones.',
    'LS_GETHOUSE':'Scoring result: ▼ White territory %d  Black dead stones %d ▼ Black territory %d  White dead stones %d',
    'LS_GETHOUSE0':'Scoring result:',
    'LS_GETHOUSE1':'Scoring result: ▼ White territory %d  Black dead stones %d ▼ Black territory %d  White dead stones %d  Komi %d',
    'LS_GIVEUP_Q':'Resign?',
    'LS_GIVEUPGAME':'%s resigned.',
    'LS_GONGJE':'Black 6½-Points advantage',
    'LS_GONGJE_EX':'Black 7½-Points advantage',
    'LS_LECTUREINFO':'Commentator: %s',
    'LS_LECTUREINFO2':'Event: %s – Commentary: %s',
    'LS_LECTUREINFO3':'Event: %s',
    'LS_LECTURER':'Lecturer: %s',
    'LS_LIMIT_REF':'The reference diagram or commentary is unavailable or too large to transfer.',
    'LS_MATCHDAY':'{0}/{1}/{2}',
    'LS_NOEXPIRE':'Lifetime member',
    'LS_PASS_AUTOGEGA':'Both players passed; switching to scoring mode.',
    'LS_PASS_DO':'%s passed.',
    'LS_PASS_QUESTION':'Pass?',
    'LS_PROG_CMT':'Status]',
    'LS_PROG_REQ':']]',
    'LS_PROG_RSP':'[[',
    'LS_REFER_NUM':'Ref. diagram %d-%d',
    'LS_RELEASERIGHT':'Master mode has been revoked.',
    'LS_RELEASETURN':'Move privileges have been revoked.',
    'LS_RES_20':'Last %d games',
    'LS_RESTARTGAME':'Player %s has returned.',
    'LS_RESULT_Q':'Agree with the result?',
    'LS_RESULTAGREE':'%s agreed with the result.',
    'LS_RESULTDISAGREE':'%s disagreed with the result.',
    'LS_RESULTDISAGREE2':'%s disagreed with the result. Returning to the game.',
    'LS_ROOMNO':'Room #%d',
    'LS_RULEBYHALT':'Stoppage rule – reconnection wait time is 3 min. After 3 disconnects, an automatic time-loss is declared.',
    'LS_RULEBYHALT2':'Stoppage rule – reconnection wait time is 5 min. After 3 disconnects, an automatic time-loss is declared.',
    'LS_RULEBYHALT3':'Stoppage rule – reconnection wait time is 5 min. After 5 disconnects, an automatic time-loss is declared.',
    'LS_RULEBYHALT4':'Stoppage rule – reconnection wait time is 10 min (tournament). After 5 disconnects, an automatic time-loss is declared.',
    'LS_SCORE_HIDDEN_END_MSG':'{0} moves until the hidden zone ends. (Ends move {1})',
    'LS_SCORE_HIDDEN_START_MSG':'Hints will be hidden! {0} moves until the hidden zone starts. (Starts move {1}, ends move {2})',
    'LS_SCORE_HILIGHT_END_MSG':'{0} moves until the highlight zone ends. (Ends move {1})',
    'LS_SCORE_HILIGHT_START_MSG':'Heavy damage will be dealt! {0} moves until the highlight zone starts. (Starts move {1}, ends move {2})',
    'LS_SECDEAD':'%d sec / %d periods / %d captures',
    'LS_SEPARATOR':'==================================',
    'LS_STARTGAME':'%s and %s have started the game.',
    'LS_SURRENDERSILVER':'AI Go resigned.',
    'LS_WAITBYHALT':'Player %s has left; waiting 3 minutes. If they do not return within 3 minutes, it will be a win on time.',
    'LS_WAITBYHALT2':'Player %s has left; waiting 5 minutes. If they do not return within 5 minutes, it will be a win on time.',
    'LS_WAITBYHALT3':'Player %s has left; waiting 10 minutes. If they do not return within 10 minutes, it will be a win on time.',
    'LS_WINBLACK_C':'Black wins by %d Points %s',
    'LS_WINWHITE_C':'White wins by %d Points %s',
    'LS_WITHDRAW_CANCEL':'Undo request cancelled.',
    'LS_WITHDRAW_NOTOK':'%s declined the undo request.',
    'LS_WITHDRAW_OK':'%s accepted the undo request.',
    'LS_WITHDRAW_Q':'%s is requesting an undo.',
    'LS_WITHDRAW_REQ':'An undo request has been sent to %s.',
    'LS_WITHDRAW_REQ2':'%s sent an undo request to %s.',
    'LV_BET_D':'Wager {0} dan',
    'LV_BET_G28':'Wager God',
    'LV_BET_G29':'God H',
    'LV_BET_G30':'God G',
    'LV_BET_G31':'God F',
    'LV_BET_G32':'God E',
    'LV_BET_G33':'God D',
    'LV_BET_G34':'God C',
    'LV_BET_G35':'God B',
    'LV_BET_G36':'God A',
    'LV_BET_INIT':'Wager beginner',
    'LV_BET_R':'Wager {0} kyu',
    'MATCH_ERR_NEGI_TODAY_MAX':'Maximum wagers per day is 100.',
    'MATCH_ERR_NO_MONEY':'Insufficient T-points.',
    'MATCH_ERR_NO_PARTNER':'No opponent found.',
    'MATCH_ERR_NOT_MATCH':'Not in matchmaking mode.',
    'MATCH_ERR_ON_MATCH':'Already searching for a match.',
    'MATCH_ERR_REJECT_MATCH':'Matchmaking was declined.',
    'MATCH_ERR_TIME_OUT':'Matchmaking timed out.',
    'MEMO_SGF_VIEW':'Game record comment',
    'MENU_AI_KATAGO':'KataGo AI (19×19)',
    'MENU_AZ_CHAKSU':'Move analysis',
    'MENU_AZ_KATA_REFER':'Reference diagram analysis',
    'MENU_AZ_KATAGO':'Deep analysis',
    'MENU_AZ_LEELA':'Leela analysis',
    'MENU_BET':'Wager',
    'MENU_BIGOFF':'Remove dame',
    'MENU_BIGON':'Mark dame',
    'MENU_BIGVIEW':'Maximise',
    'MENU_CHANGECAST':'Change relay room',
    'MENU_CHGLINK':'Change link',
    'MENU_CLOSEBR':'Close reference diagram',
    'MENU_CLSBOARD':'Delete',
    'MENU_CONN_NEW':'New game connection',
    'MENU_COPY':'Copy',
    'MENU_COPYALL':'Copy all',
    'MENU_EDITMENU':'Edit',
    'MENU_LASTSUSUN':'Go to last move',
    'MENU_LINE9_REQ':'9×9 request (friendly)',
    'MENU_LIVE_ENDGUMTO':'End review',
    'MENU_LIVE_GUMTO':'Start review',
    'MENU_LIVE_MENU':'Review menu',
    'MENU_LIVE_REGUMTO':'Reset',
    'MENU_MAKEREF':'Create reference diagram',
    'MENU_MAKEREF_SHORT':'Generate best move',
    'MENU_MISS_B':'Black mistake analysis',
    'MENU_MISS_W':'White mistake analysis',
    'MENU_NEGI_FMT':'{0}0,000 wager',
    'MENU_NEGI0':'No wager',
    'MENU_OPENNEW':'Open',
    'MENU_RELAY':'Create relay / commentary room',
    'MENU_RELAY_TEXT':'Text commentary',
    'MENU_RELAY_VIDEO':'Voice commentary',
    'MENU_SETLAST':'Go to last move',
    'MENU_SGF_MENU':'Review',
    'MENU_SORTGROUP':'Sort by club',
    'MENU_STEPREF':'Step through reference',
    'MENU_TRANSLATE':'Translate',
    'MENU_VIEWPOPUP':'Pop-up',
    'MI_WARNING_DEAKUK':'Friendly games are possible between my multi-user accounts.',
    'MPOS_FMT_OTHER':'Participating in [{0}].',
    'MPOS_FMT_SAME':'Currently {0} on this server.',
    'MPOS_FMT_SVR':'Move to [{0}] server.',
    'MPOS_FMT_SVR_EX':'Moving to [{0}] server.',
    'MPOS_NO_LOGIN':'Not logged in.',
    'MSG_AIJUDGE_01':'Request AI judgement?',
    'MSG_AIJUDGE_02':'(If there are still playable moves, judgement cannot be made.)',
    'MSG_AIJUDGE_03':'*AI judgement is only performed at the end of the game. If there are still playable moves, the game will resume regardless of advantage.',
    'MSG_AIJUDGE_04':'*Judgement is based on the results of deep position analysis.',
    'MSG_AIJUDGE_ING':'AI judgement in progress. Please wait for the result.',
    'MSG_AIJUDGE_ING_PARTNER':'Your opponent has requested AI judgement. Please wait for the result.',
    'MSG_AIJUDGE_RESULT':'* Judgement result  –  White territory: {0} (win rate: {1}%)  –  Black territory: {2} (win rate: {3}%)',
    'MSG_AIJUDGE_RESULT1':'Result: {0}  White territory: {1} (win rate: {2}%)  Black territory: {3} (win rate: {4}%)  {5}',
    'MSG_AIJUDGE_RESULT2':'{0} wins.',
    'MSG_CHANGE_SGFLINK':'Enter the download URL.',
    'MSG_CHATBOX_AI_HINT':'Free hints remaining: {0}',
    'MSG_CHATBOX_AI_UNDO':'Free undo requests remaining: {0}',
    'MSG_DAEKUK_READY':'Preparing for game...',
    'MSG_DOWNROOM':'Downloading game information...',
    'MSG_ENABLETURN':'Cross-play is only available in review mode.',
    'MSG_GAMEREADY':'Preparing the game.',
    'MSG_GAMEREQ':'Request in progress',
    'MSG_GAMESTART':'Starting the game.',
    'MSG_GOBACK':'Reconnecting to the previous server.',
    'MSG_JOIN_FOR_AI_HINT':'* Register as a paid member for 100 hints per day',
    'MSG_JOIN_FOR_AI_UNDO':'* Register as a paid member for 50 undo requests per day',
    'MSG_JOIN_FOR_CREATE_GIBO':'* Register as a paid member for free recommended move / reference diagram creation',
    'MSG_JOIN_FOR_CREATE_REALTIME_REFE':'* Register as a paid member for free AI commentary',
    'MSG_LACKGAMEFEE_P':'%s has insufficient game fees and cannot play.',
    'MSG_MATCHING':'Searching for a game...',
    'MSG_NOEVENT':'No events.',
    'MSG_NOOPENGAME':'No open game rooms are available.',
    'MSG_OPENMEMO':'Open message box',
    'MSG_REGBAD':'User has been blocked.',
    'MSG_REJECT':'{0} has blocked all incoming communication. This applies to game requests, invitations, chat, and messages.',
    'MSG_TOP3_ICON':'Top 3 wagers earn an extra 10% of the profit!',
    'MSG_UNREADMEMO':'You have {0} unread message(s).',
    'MSG_USEITEM_BET':'This item can be used for wager predictions.',
    'MSG_USEITEM_EMPTY':'No items in inventory.',
    'MSG_USEITEM_GAME':'This item can be used for games.',
    'NFMSG_AUTO_BET':'*Auto-wager (9-dan games). 10% of the lower player\'s points are wagered. Max 500M T-points (min 1M). Players may wager on themselves up to 2 times before move 20.',
    'NFMSG_NEGI_STARTEX':'T-Point game has started. Winner receives %s points. Continue?',
    'NMSG_AIZEN6_9DAN':'Uses the ZEN7 Premium Server for 8–9 dan players.',
    'NMSG_AIZEN6_INFO':'Win and receive 1,000,000 points! Game records are saved! (From move 11, win/loss is recorded)',
    'NMSG_AIZEN6_INFO2':'(Note) Cash used for AI games is non-refundable.',
    'NOREAD_MEMO':'There are unread messages in your message box.',
    'NOTICE_ZEN6_PLAY':'Cash is required for Zen games.',
    'NOTIFY_HIDEPOPUP':'Hidden screens',
    'OMOKRULE_NORMAL':'Normal',
    'ON_GAMEREADY':'Preparing',
    'ON_LIVECAST':'Relay room',
    'ON_LIVEEXP':'Lecture room',
    'OPT_ALLOW':'Allowed',
    'OPT_BET':'Wagers allowed',
    'OPT_BET_AUTO':'Auto-wager',
    'OPT_BET_SECTION':'Section wager details',
    'OPT_CHINARULE':'Chinese rules',
    'OPT_NOTALLOW':'Not allowed',
    'OPT_NOTUSE':'Disabled',
    'OPT_SETBACK':'One move undo allowed',
    'OPT_TERRITORY':'Position analysis disabled',
    'OPT_USE':'Enabled',
    'OPWARN_GAMEINFO_EXIST':'Pre-set game conditions already exist.',
    'OPWARN_NOT_SUPPRT':'This staff menu feature is not currently supported.',
    'PAYMSG_CASH':'{0} Cash will be consumed.',
    'PAYMSG_ITEM':'{0} item(s) will be consumed.',
    'PM_AI_HINT':'Hint – {0} T-points',
    'PM_AI_UNDO':'Undo request – {0} T-points',
    'PM_AUTOREQ':'Auto-match request – {0} points',
    'PM_CAPTION_AUTOREQ':'Auto-match request',
    'PM_CAPTION_DEAKUKREQ':'Game request',
    'PM_CAPTION_TERITORY':'Position analysis',
    'PM_DEAKUKREQ':'Game request – {0} points',
    'PM_MYMONEY':'Points held',
    'PM_NOTICE':'Use this feature?',
    'PM_PAYMONEY':'Cost per use',
    'PM_TERRITORY':'Position analysis – {0} points',
    'PM_TPOINT':'Go Points',
    'PRETEXT_CALL_OP':'Please enter your inquiry. (200 characters max)',
    'PRINT_LOGO':'Toyo-igo (www.toyo-igo.com) game record print',
    'PRINT_TITLE':'[Players] White ({0}) vs Black ({1}) [Time]{2} [Handicap]{3} [Time]{4} [Result]{5} [Moves]{6}',
    'PRO_LIVE_TXT':'Pro live relay',
    'PROBIGMATCHNOTE_START':'A Pro Big Match: {1} vs {2} has started in Room #{0}.',
    'Q_ZEN_CERTIFY':'What is the ZEN7 certification mark?',
    'QUESTION_PASSWORD':'Please enter the password.',
    'REGBAD_AUTOREJECT':'Automatically declined (blocked user)',
    'REJ_GAME1':'%s declined the game request.',
    'REPORT_CASE0':'Misconduct in game',
    'REPORT_CASE1':'Misconduct in chat',
    'REPORT_CASE2':'Offensive ID',
    'REPORT_CASE3':'Misconduct while spectating',
    'REPORT_CASE4':'Other',
    'REPORT_ST0':'Select reason (required)',
    'REPORT_ST1':'The game record and chat content will be submitted. Processing may take some time; you will be notified once confirmed.',
    'REPORT_ST2':'False reports may result in usage restrictions.',
    'REPORT_ST3':'Up to 3 reports allowed per game.',
    'RESULT_CANCEL':'Void',
    'RESULT_STR':'%s %s %s.',
    'RESULT_STR0':'%s and %s %s.',
    'RESULT_STR1':'The game between %s and %s resulted in %s.',
    'RMMENU_ANALYZE_KATA':'KataGo analysis',
    'RMMENU_ANALYZE_LEELA':'LeelaZero analysis',
    'RMMENU_FULLSCREEN':'Full screen|2',
    'RMMENU_HIDECHAT':'Hide chat|0',
    'RMMENU_POJUNG':'Fuseki / Joseki',
    'RMMENU_SAVE':'Save game record|3',
    'RMMENU_SCRAP':'Split diagram',
    'RULE_STR0':'Even: Black 6½ komi',
    'RULE_STR0_EX':'Even: Black 7½ komi',
    'RULE_STR1':'Fixed colour',
    'RULE_STR2':'Life & death %d: Even',
    'RULE_STRDUM':'Handicap %d stones',
    'RULE_STRDUM2':'Handicap %d stones: Black komi %d Points',
    'SEC_01':'0.1 sec',
    'SEC_02':'0.2 sec',
    'SEC_03':'0.3 sec',
    'SEC_04':'0.4 sec',
    'SEC_05':'0.5 sec',
    'SEC_10':'1.0 sec',
    'SEC_15':'1.5 sec',
    'SEC_20':'2.0 sec',
    'SEC_30':'3.0 sec',
    'SERVICE_NOTREADY':'Service is being prepared.',
    'SETUP_PUTTYPE':'Move method',
    'SETUP_PUTTYPE_FLOATING':'Confirm button',
    'SETUP_PUTTYPE_ONE_CLICK':'Single click',
    'SETUP_PUTTYPE_TWO_CLICK':'Double click',
    'SGFANALYZE_ERROR':'An error occurred in the game record analysis service. Please try again later.',
    'SGFANALYZE_NOTREADY':'Game record analysis service is being prepared. Please try again later.',
    'SGFANALYZE_SUPPORT':'The game record analysis service only supports 19×19 game records.',
    'SGFANALYZE_WAIT':'Waiting for game record analysis results.',
    'SGFANZLYZE_PLAYER_WARN_MSG':'Cannot be used during a game.',
    'SGFANZLYZE_WAIT':'Waiting for game record analysis results.',
    'SHARED_MEMO':'Share via message',
    'SHARED_SNS':'Share via SNS',
    'SS_RESULTEQUAL':'{0} and {1} drew the game.',
    'SS_RESULTWIN':'{0} wins – {1}',
    'ST_BCLICK':'Select Black',
    'ST_BET':'Wager',
    'ST_BETMONEY':'Wager points',
    'ST_CASTROOM':'Select game to connect to',
    'ST_CASTURL':'Use external media (UCC site)',
    'ST_CHEVENTENDTIME':'Red envelope wager end',
    'ST_CHEVENTROOMMONEY':'Red envelope room points',
    'ST_CHNLKEY':'Channel/Key',
    'ST_COMMANTEXP':'Commentary viewing',
    'ST_COMMENT':'Title',
    'ST_COMMENTATOR':'Commentator',
    'ST_CONTEST_HOI':'',
    'ST_CONTEST_JE':'',
    'ST_CONTEST_KUK':'Game',
    'ST_CONTEST_ROUND':'Round',
    'ST_CONTEST_TIME':'Time settings',
    'ST_CONTEST_TNM':'Tournament',
    'ST_CONTESTNN':'Category',
    'ST_CUR_RES':'Current record',
    'ST_CURSUSUN':'Current move',
    'ST_DATE':'Date',
    'ST_DOBET':'Place wager',
    'ST_EMPTY':'None',
    'ST_EMPTYGIBO':'Empty game record',
    'ST_ENDBET':'Wager closed',
    'ST_EXPROOM':'Event info',
    'ST_EXPROOM2':'Event / commentator info',
    'ST_FIND_LOCAL_GIBO':'* File import supports GIB and SGF formats.',
    'ST_FINDROOM':'Search by room number',
    'ST_FIRST':'1st phase',
    'ST_HONGBBAO':'Red envelope settings',
    'ST_INFOBET':'Additional info',
    'ST_INVITE0':'Invitee',
    'ST_INVITE2':'Invitation',
    'ST_ITEMDOU':'Double item',
    'ST_ITEMFIX':'Fixed item',
    'ST_ITEMINS':'Insurance item',
    'ST_MYBET':'My wager',
    'ST_MYPOINT':'My points',
    'ST_NO_VIEW_TODAY':'Don\'t show today.',
    'ST_NO_VIEW_WEEK':'Don\'t show this week.',
    'ST_PARTNERID':'Opponent ID',
    'ST_PAYPOINT':'Points consumed',
    'ST_PBET':'Wager section',
    'ST_PMONEY':'Estimated win',
    'ST_POSINFO':'Location info',
    'ST_PRATIO':'Odds',
    'ST_PROGIBO_CONT':'Pro tournament records',
    'ST_PROGIBO_NEW':'Recent pro records',
    'ST_RECENTLY20':'Last 20 games',
    'ST_REL_REC5':'Opponent\'s last 5 games',
    'ST_REL_WIN':'Opponent wins',
    'ST_RES2':'Result',
    'ST_ROOMLEVEL':'Access level',
    'ST_ROOMPHASE_SECTION1':'Section 1',
    'ST_ROOMPHASE_SECTION2':'Section 2',
    'ST_ROOMPHASE_SECTION3':'Section 3',
    'ST_ROOMPHASE_SECTION4':'Section 4',
    'ST_ROOMTYPE':'Room type',
    'ST_RPOINT':'Rank points',
    'ST_SECOND':'2nd phase',
    'ST_SITE':'Site',
    'ST_TEST':'Test',
    'ST_THIRD':'3rd phase',
    'ST_TIER':'Tier',
    'ST_TOTSUSUN':'Total moves',
    'ST_TPOWER':'Internal power',
    'ST_USECAST':'How to use external media',
    'ST_VIEWBET':'View details',
    'ST_VISION':'Waiting room',
    'ST_WCLICK':'Select White',
    'SUPERMATCHNOTE_START':'A Super Match: {1} vs {2} has started in Room #{0}.',
    'TAB_GAMEINFO':'Game info',
    'TAB_INPUTEXP':'Edit commentary',
    'TAB_OPBANK':'Payment confirmation',
    'TAB_OPCALL':'1:1 help',
    'TAB_OPHELP':'Request judgement',
    'TAB_OPREPORT':'Report game/chat',
    'TAG_DUPLICATE_HELP':'**help**',
    'TAG_VIP':'**VIP**',
    'TASK_FMTEXP':'Commentary relay #%d',
    'TASK_FMTGAME':'%d game(s)',
    'TASK_FMTLEC':'Review / commentary #%d',
    'TASK_FMTLNK':'Live relay #%d',
    'TASK_VIEWEDIT':'Game editing',
    'TASK_VIEWSGF':'SGF sharing',
    'TEXP_GIBOTITLE':'%s – %s (%d moves)',
    'TEXP_LIVECAST':'Relay – %s',
    'TEXP_LIVECAST_END':'Relay ended – %s',
    'TEXP_LIVEEXP':'In lecture – Teacher',
    'TEXP_LIVEEXP_END':'Lecture ended – Teacher',
    'TEXP_LIVEEXP_END2':'Lecture ended – Spectator',
    'TEXP_LIVEEXP_GAME':'Room #%d – Game',
    'TEXP_LIVEEXP2':'In lecture – Spectator',
    'TEXP_SUBGAME':'Room #%d – In game – %s (%d moves)',
    'TEXP_SUBGAME_CONNECT':'Connecting...',
    'TEXP_SUBGAME_END':'Room #%d – Game over (%s) – %s (%d moves)',
    'TEXP_SUBGAME_HOLD':'Room #%d – Game paused – %s (%d moves)',
    'TEXP_SUBGAME_READY':'Room #%d – Preparing',
    'TEXP_TEXTEXP':'Commentating – %s (%d moves)',
    'TEXP_TEXTEXP_END':'Commentary ended (%s) – %s (%d moves)',
    'TEXP_TEXTEXP_READY':'Preparing commentary',
    'TEXP_VIEWGAME':'In game – %s (%d moves)',
    'TEXP_VIEWGAME_BOKGI':'Reviewing (%s) – %s (%d moves)',
    'TEXP_VIEWGAME_END':'Game over (%s) – %s (%d moves)',
    'TEXP_VIEWGAME_HOLD':'Game paused – %s (%d moves)',
    'TEXP_VIEWGAME_READY':'Preparing',
    'TEXP_VIEWGAME_WATCH':'Spectating – %s (%d moves)',
    'TEXP_VIEWGAMEEX':'In game – %s (%d moves)',
    'TEXP_VIEWGAMEEX_END':'Game over (%s) – %s (%d moves)',
    'TEXP_VIEWGAMEEX_HOLD':'Game paused – %s (%d moves)',
    'TEXP_VIEWGAMEEX_WATCH':'Spectating – %s (%d moves)',
    'TEXP_VIEWGAMEEXNAGI':'In game – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMEEXNAGI_END':'Game over (%s) – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMEEXNAGI_HOLD':'Game paused – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMEEXNAGI_WATCH':'Spectating – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMENAGI':'In game – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMENAGI_END':'Game over (%s) – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMENAGI_HOLD':'Game paused – %s (%d moves) Point Go %s',
    'TEXP_VIEWGAMENAGI_WATCH':'Spectating – %s (%d moves) Point Go %s',
    'TEXP_VIEWGIBO_END':'Game result (%s) – %s (%d moves)',
    'TITLE_CALLOP':'Help Centre',
    'TITLE_EVENT':'Toyo-igo Event',
    'TITLE_FINDUSER':'Find Location',
    'TITLE_GAMEREQ': '%d Game Request',
    'TITLE_GIBO':'Game Records',
    'TITLE_INVITEREQ':'%×% Room Invitation',
    'TITLE_MEMOERR':'Message Failed',
    'TITLE_NOTICE_REG':'Announcement Registration',
    'TITLE_USERINFO':'Member Info',
    'TM_RESERVEDREQ':'Reserved game request',
    'TO_CHEER_FIRECRACKER':'Fireworks for %s',
    'TO_CHEER_ROSE':'Roses for %s',
    'TOKEN_DATE':'Y/M/D H:M',
    'TON_RESULT_AUTO_GEGA':'Judgement result: %s',
    'TON_RESULT_AUTO_GEGA_TITLE':'Tournament Judgement Result',
    'TON_WON_THE_GAME':'"%s" has won.',
    'TOOL_ALPHABET':'Letters',
    'TOOL_ALTERNATIVE':'Black/White cross',
    'TOOL_BLACKBLACK':'Black stone / Black stone',
    'TOOL_BLACKWHITE':'Black stone / White stone',
    'TOOL_CANCEL':'Cancel',
    'TOOL_CIRCLE':'Circle',
    'TOOL_CROSS':'X',
    'TOOL_ERASE':'Erase',
    'TOOL_NUMBER':'Numbers',
    'TOOL_RECTANGLE':'Rectangle',
    'TOOL_TRIANGLE':'Triangle',
    'TOOL_WHITEBLACK':'White stone / Black stone',
    'TOOL_WHITEWHITE':'White stone / White stone',
    'TOUSER_BETCHEER_FIRECRACKER':'Firework cheer for %s',
    'TOUSER_BETCHEER_TYPE1':'1 rose cheer for %s',
    'TOUSER_BETCHEER_TYPE10':'10 rose cheers for %s',
    'TOUSER_BETCHEER_TYPE30':'30 rose cheers for %s',
    'TOUSER_BETCHEER_TYPE5':'5 rose cheers for %s',
    'TOUSER_BETCHEER_TYPE60':'60 rose cheers for %s',
    'TOUSER_BETCHEER_TYPE90':'90 rose cheers for %s',
    'TS_BPLAYER':'Black player',
    'TS_DEADSTONE':'%d captures',
    'TS_GCEXP':'Game conditions',
    'TS_GTEXP':'Time limit',
    'TS_KIND':'Type',
    'TS_METHOD':'Move method',
    'TS_NOLIMITGAME':'No time limit',
    'TS_OFFAIR':'Off air',
    'TS_ONAIR':'On air',
    'TS_PLAYTEST':'Try move',
    'TS_REMAINDEAD':'Captures',
    'TS_REMAINSEC':'Byo-yomi',
    'TS_REMAINTIME':'Remaining time',
    'TS_REMOVE_RIGHT':'Remove master',
    'TS_REMOVE_TRYTURN':'Remove cross-play moves',
    'TS_REPLAYTEST':'Re-do try move',
    'TS_RULE':'Handicap',
    'TS_SECLIMIT':'%d sec / %d periods',
    'TS_SECLIMITDEAD':'%d sec / %d periods / %d captures',
    'TS_SETRIGHT':'The master has granted play privileges.',
    'TS_SETRIGHT2':'The master has changed to %s.',
    'TS_SETTRYTURN':'Now in cross-play mode with the master.',
    'TS_SETTRYTURN2':'Now in cross-play mode between the master and {0}.',
    'TS_TIMECOND':'%d min %d sec / %d periods',
    'TS_TIMECONDEXP':'%d h %d min %d sec / %d periods',
    'TS_TIMECONDEXP2':'%d h %d min : %d min %d sec / %d periods',
    'TS_WPLAYER':'White player',
    'TT_CLOSEBR':'Right-click board',
    'TT_DIALOG2VIEW':'Pin to main screen',
    'TT_HIDE_M':'Hide media',
    'TT_MAXMIN':'Maximise / Minimise',
    'TT_SHOW_M':'Show media',
    'TT_SHOWBOARD':'Relay board',
    'TT_SHOWEXP':'Commentary',
    'TT_SWAPBOARD':'Swap main board',
    'TT_TOPALWAYS':'Always on top',
    'UPDATEMSG_PERSON':'Updating waiting player list.',
    'UPDATEMSG_ROOM':'Updating game room list.',
    'UPDATEMSG_WAITPERSON':'Downloading waiting player data.',
    'UPDATEMSG_WAITROOM':'Downloading game room data.',
    'USER_NOTIFY':'has logged in.',
    'UST_AI_INSURE':'ZEN7 certification mark',
    'UST_CASH':'Cash held',
    'UST_INFO_0':'Tier',
    'UST_INFO_1':'RP',
    'UST_INFO_2':'Record',
    'UST_INFO_3':'Japan rank',
    'UST_INFO_4':'World rank',
    'UST_INFO_BET':'Wager prediction info',
    'UST_INFO_ITEM':'Item info',
    'UST_INFO_LINE9':'Other game info',
    'UST_LINE9_0':'9×9 tier',
    'UST_LINE9_1':'9×9 RP',
    'UST_LINE9_2':'9×9 record',
    'UST_LINE9_3':'9×9 Japan rank',
    'UST_LINE9_4':'9×9 World rank',
    'UST_LINE9_PT':'RP',
    'UST_LINE9_RES':'Record',
    'UST_LINE9_RK':'Rank',
    'UST_OWN_PRPERTY':'Toyo-igo assets',
    'UST_POINTMYO':'Tsumego points',
    'UST_POINTRANK':'Rank points',
    'UST_RES_BET':'Wager record',
    'UST_TPOINT':'T-Points held',
    'UST_TPOINTCHM':'M Points',
    'UST_TPOINTREC':'Personal record',
    'WARN_AI_LIMIT_1':'Undo cannot be requested on the first move.',
    'WARN_AI_LIMIT_5':'Available from move 5 onwards.',
    'WARN_AI_ONLY_ONE':'This feature is unavailable.',
    'WARN_ALREADY_JOIN':'Already a member of this room or game room.',
    'WARN_ALREADYLOGIN':'This ID is already in use. Disconnect the previous session and try again?',
    'WARN_BET_ALL':'You have already wagered on this game {0} time(s). See the "Details" tab for your wagers.',
    'WARN_BET_MORE':'You have already wagered on this game {0} time(s).',
    'WARN_BET_MORE2':'You have already wagered on this game {0} time(s). Wagering again is a paid member feature.',
    'WARN_CALL_RESULT':'## Staff have been called.',
    'WARN_CALL_RESULT1':'Staff are currently unavailable. Your message has been delivered to staff.',
    'WARN_CANNOT_JUDGE':'AI judgement is not available yet. Returning to the game.',
    'WARN_CHECKOUT1':'You have unfinished games and cannot log out.',
    'WARN_CHECKOUT2':'You have unfinished games and cannot change servers.',
    'WARN_CHEER_ITEM_NOBET':'You must place a wager to use cheer items.',
    'WARN_CHEER_ITEM_ONGAME':'Cheer items can only be used during a game.',
    'WARN_CHEER_ITEM_PLAYER':'Players cannot use cheer items.',
    'WARN_COMMENTATOR':'Please enter the commentator name.',
    'WARN_CONTESTSVR':'This is a tournament server. Only registered tournament participants are supported.',
    'WARN_CONTESTSVR2':'This is a tournament server. Only registered tournament participants are supported. Tournament participants should enter their designated room before the match begins.',
    'WARN_CONTESTSVR3':'This is a tournament server. 1:1 chat requests and other games are not available.',
    'WARN_COUNTOVER_ANALYZE_REF':'Free members cannot create recommended moves. Register as a paid member for unlimited use.',
    'WARN_DETAIL_TERITORY_COUNTOVER':'Free members can use this 5 times per day. Register as a paid member for unlimited use.',
    'WARN_DOWNLOADFAIL':'Failed to download the game record. Please try again later.',
    'WARN_EXIST_REF':'A recommended move or reference diagram already exists.',
    'WARN_EXIT_READYUSER':'Your opponent has left the room.',
    'WARN_GAME_CANCEL':'Your opponent left the room; the game has been cancelled.',
    'WARN_GAME_ERROR':'There is an error in the game information.',
    'WARN_GAME_PLAY':'Cannot place a move at this time.',
    'WARN_GAMEREQ_EXIT':'Your opponent left the room. Please choose another opponent.',
    'WARN_GAMEREQ_MINE':'You cannot play a game against yourself.',
    'WARN_GAMEREQ_READY':'You cannot send a game request while negotiations for another game are in progress.',
    'WARN_HASNOCIRCLE':'You are not registered in any clubs.',
    'WARN_HELP_LIMIT_9LINE':'Judgement requests are not available in 9×9 games. Please use the AI judgement function.',
    'WARN_HIDDENROOM':'Please enter the live relay room number.',
    'WARN_HINT_EXIST':'A hint already exists.',
    'WARN_IMPOSSIBLE_1ON1':'1:1 help is not available during a game.',
    'WARN_IMPOSSIBLE_JUDGMENT_REQ':'Judgement requests are only available during a game.',
    'WARN_INVALID_LINK':'Invalid URL.',
    'WARN_JUDGE_ALREADY':'AI judgement has already been performed on the current move.',
    'WARN_JUDGE_ERROR':'AI judgement error. ({0})',
    'WARN_JUDGE_LIMIT_FMT':'AI judgement is not available before move {0}.',
    'WARN_JUDGE_LIMIT50':'AI judgement is not available before move 50.',
    'WARN_JUDGE_NORESPONSE':'The AI judgement server is not responding.',
    'WARN_JUDGE_WAIT':'{0} has requested AI judgement. Please wait for the result.',
    'WARN_JUDGMENT_REQ_EXP1':'If you request staff intervention, staff will review the position.',
    'WARN_JUDGMENT_REQ_EXP2':'Note: staff will confirm the final result.',
    'WARN_LIMIT_CHAT_3SECOND':'To keep chat comfortable, repeated posting is prohibited. Please wait before posting again.',
    'WARN_LIMIT_CHAT_REPEAT':'To keep chat comfortable, repeated messages are prohibited.',
    'WARN_LIMITFRIEND':'Only friendly games are available.',
    'WARN_LIMITONGAME':'Already in a game; only friendly games are available. (Simul)',
    'WARN_LIMITUPDOWN':'A ranked game is not possible with a difference of 1 dan/kyu or more.',
    'WARN_LIMITUPDOWNPRO':'Professional players cannot play ranked games.',
    'WARN_LIVECHNL':'Please enter the channel/key for the UCC site.',
    'WARN_MAKEROOM0':'On this server, only instructors can create lecture and live relay rooms.',
    'WARN_MAKEROOM1':'On this server, you do not have permission to create lecture or live relay rooms.',
    'WARN_MAKEROOM2':'Please select a game room to connect to.',
    'WARN_MAKEROOM3':'The selected room #%d has been deleted. Please select again.',
    'WARN_MAKEROOM4':'The options for room #%d have changed. Please select again.',
    'WARN_MAKEROOM5':'The server is currently unable to create new game rooms.',
    'WARN_MAKEROOM6':'You are already in a lecture/live relay room. Only one is allowed.',
    'WARN_MAKEROOM7':'Already participating in room #%d; cannot connect.',
    'WARN_MATCHFAIL_REASON1':'%s does not have enough T-money to proceed with the game.',
    'WARN_MATCHFAIL_REASON12':'Only 7 games per day are allowed against the same player.',
    'WARN_MATCHFAIL_REASON2':'Not enough Go Points to proceed with the game.',
    'WARN_MATCHFAIL_REASON3':'You already have a wager game in progress. Only one multi-room wager game is allowed at a time.',
    'WARN_MAXVIEW':'You can join a maximum of 3 rooms at once. (4 for paid members)',
    'WARN_MAXVIEW_CHANNEL':'You are already in a voice review / live relay room. Only one is allowed.',
    'WARN_MEMODEL0':'Please select a message to delete.',
    'WARN_MEMODEL1':'Delete all {0}?',
    'WARN_MEMODEL2':'There are unread messages in {0}. Delete all?',
    'WARN_MEMODEL3':'The selected messages include unread ones in {0}. Delete?',
    'WARN_MULTISEND':'A maximum of {0} messages can be sent at once.',
    'WARN_MYAIJUDGE':'Only available on your own turn.',
    'WARN_MYGEGA':'You can request scoring on your own turn.',
    'WARN_MYSKIP':'You can pass one move on your own turn.',
    'WARN_NO_PERMISSION_RANK':'This feature is unavailable during ranking games.',
    'WARN_NOMONEY':'Insufficient points.',
    'WARN_NOT_AVAILABLE':'We are sorry. Maintenance is in progress.',
    'WARN_NOTCONT':'Please enter a title and message.',
    'WARN_NOTEXISTROOM':'The specified room does not exist.',
    'WARN_NOTFOUND_ID':'Not a registered member.',
    'WARN_NOTFOUNDGIBO':'Could not find the requested game record.',
    'WARN_NOTRECV':'Please enter a recipient.',
    'WARN_NOTSUPPORT_DEAD':'The current program does not support life-and-death games.',
    'WARN_OFFLINE_ID':'The member is not currently connected.',
    'WARN_PASSWORD':'Passwords do not match.',
    'WARN_PLAYER_BET_LIMIT':'You cannot wager if either player is below your rank. (8-dan / 9-dan only)',
    'WARN_POSOKBET':'Unavailable for wager game participants.',
    'WARN_REJECT_INVITE':'"%s" declined the invitation.',
    'WARN_REJECT_INVITE_LIMITCONDITION':'"%s" has all 3 game screens open and cannot accept an invitation.',
    'WARN_REJECT_INVITE_ONDAEKUK':'"%s" is currently in a game or lecture and cannot respond to invitations.',
    'WARN_REJECT_INVITE_OTHERINVITE':'"%s" is currently negotiating another game and cannot accept an invitation.',
    'WARN_REJECT_INVITE_SETUP':'"%s" has their invitation option set to "decline".',
    'WARN_REJECT_RCV':'%s has declined all incoming communication.',
    'WARN_REJECT_REQ':'"%s" declined the game request.',
    'WARN_REJECT_REQ_LIMITCONDITION':'"%s" has all 3 game screens open and cannot accept game requests.',
    'WARN_REJECT_REQ_ONDAEKUK':'"%s" is currently in a game or lecture and cannot accept game requests.',
    'WARN_REJECT_REQ_OTHERINVITE':'"%s" is negotiating another game and cannot accept a new game request.',
    'WARN_REJECT_REQ_SETUP':'"%s" has their game request option set to "decline".',
    'WARN_REJECT_TIMEOUT':'"%s" is not responding.',
    'WARN_REJGAME':'"%s" is not accepting game requests at this time.',
    'WARN_REJINVITE':'"%s" is not accepting invitations at this time.',
    'WARN_REPORT_RESULT1':'Report submitted.',
    'WARN_REPORT_RESULT2':'Please select a report reason.',
    'WARN_REPORT_RESULT4':'Only a player during a game can submit a report.',
    'WARN_REQ_AIJUDGE':'Only available after move {0}.',
    'WARN_REQ_GEGA':'Scoring cannot be requested within the first {0} moves.',
    'WARN_RESTRICT_TERITORY_BYLEVEL':'In wager games, paid members can use position analysis up to move 50 only if using a "Double" item or wagering at the maximum limit.',
    'WARN_RESTRICT_TERITORY_BYMAKE':'Position analysis cannot be performed during game condition negotiations.',
    'WARN_RESTRICT_TERITORY_BYPLAYER':'Players in a wager game cannot use position analysis.',
    'WARN_SAMESERVER':'This is the same server you are currently on.',
    'WARN_SELUSER':'Please select a user to assign privileges to.',
    'WARN_TERRI_LIMIT_SUSUN':'{0} cannot use position analysis beyond move {1}.',
    'WARN_TPOINT_FOR_AI_HINT':'Hints are for paid members only.',
    'WARN_TPOINT_FOR_AI_UNDO':'Undo requests are for paid members only.',
    'WARN_TPOINT_FOR_CREATE_GIBO':'Free members need {0} points for recommended move / reference diagram creation.',
    'WARN_TPOINT_FOR_CREATE_REALTIME_REFE':'Free members need {0} T-points for AI commentary.',
    'WARN_UPLOADFAIL':'Failed to upload the game record. Please try again later.',
    'WARN_USED_FOR_A_DAY':'You have exhausted your daily usage limit.',
    'WARN_WRONG_POSITION':'That is not a valid move.',
    'WARN_YOUNGBOY_NO_NEGI':'The opponent requested Point Go; it was automatically declined. Underage members cannot use Point Go.',
    'WBET_CLOSESECTION':'Wagering has closed.',
    'WBET_FULLITEM':'Cannot use any more items.',
    'WBET_MONEYFIRST':'Wager points are required to use this item.',
    'WBET_MONEYLIMIT':'Exceeded the maximum wagerable amount. (max {1} for {0})',
    'WBET_NOCHOICE':'Please select a winner to predict.',
    'WBET_NOITEM':'No items in your inventory.',
    'WBET_NOMONEY':'Insufficient points.',
    'WBET_SAMEITEM':'Items of the same type cannot be used together.',
    'WIN_BANZIP':'½ Point',
    'WIN_ZIP':'%d Points',
    'WIN_ZIPBAN':'%d½ Points',
    'WMSG_DRAWREQ1':'Request a draw? Maximum %d draw requests.',
    'WMSG_DRAWREQ2':'Request a draw? %d requests remaining.',
    'WMSG_GUEST_GAMEREQ':'Guests cannot request games. Log in (register as a member)?',
    'WMSG_NO_SAMEGEUP_EXIST':'No members of the same rank are currently online.',
    'WMSG_NO_SAMEGEUP_EXIST_9LINE':'No members with the same rating points are currently online.',
    'WMSG_NOTSUPPORT':'This feature is not supported.',
    'WWIN_FMT':'White {0} wins',
    'ZEN_CERTIFY':'ZEN7 certification mark',
    'ZEN_CERTIFY_CP':'ZEN7 rank certification',
    'ZENCERT_WIN2':'You have obtained a new certification mark.',
    'MENU_TERRI_NORMAL':'Standard',
    'MENU_TERRI_DETAIL':'Detailed',
    'TS_KIND':'Type',
    'GT_RULE0':'Even',
    'GT_RULE1':'Fixed colour',
    'GT_RULE2':'2-stone',
    'GT_RULE3':'3-stone',
    'GT_RULE4':'4-stone'
  };

  // ── Server name translations (applied directly to G_VAR.SERVER_JP) ───────
  const SERVER_NAMES = {
    'プレミアムサーバー': 'Premium',
    'イベントサーバー':   'Event',
    '大会サーバー':       'Tournament',
    'グローバルサーバー': 'Global',
    '高段者サーバー':     'High Dan',
    '初級者サーバー':     'Beginner',
    '国際サーバー':       'International',
    '日本サーバー':       'Japan',
  };

// ── Remove TimeTree banner ────────────────────────────────────────────────
    function removeBanner() {
        const banner = document.getElementById('container');
        if (!banner) {
            setTimeout(removeBanner, 100);
            return;
        }
        // Find and click the close button (the second img inside the banner)
        const closeBtn = banner.querySelectorAll('img')[1];
        if (closeBtn) {
            closeBtn.click();
            console.log('[toyo-translate] Banner closed via click');
        } else {
            setTimeout(removeBanner, 100);
        }
    }
    // Wait longer for the app to fully initialise before clicking
    setTimeout(removeBanner, 3000);

  // ── Patch functions ───────────────────────────────────────────────────────

  function escapeXml(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function patchLangXml(xml) {
    return xml.replace(
      /<xlang>[\s\S]*?<\/xlang>/g,
      function (block) {
        const keyMatch = block.match(/<xkey>([^<]+)<\/xkey>/);
        if (!keyMatch) return block;
        const key = keyMatch[1].trim();
        if (!(key in T)) return block;
        return block.replace(
          /<xtext>[^<]*<\/xtext>/,
          '<xtext>' + escapeXml(T[key]) + '</xtext>'
        );
      }
    );
  }

  function patchGibo(text) {
    try {
      const data = JSON.parse(text);
      if (data.list) {
        data.list = data.list.map(function (r) {
          if (r.CateName) {
            r.CateName = r.CateName
              // Game type (must come first)
              .replace(/昇降級/g, 'Ranked')
              .replace(/親善/g, 'Friendly')
              // Handicap — specific patterns before generic ones
              .replace(/(\d+)目置碁/g, '$1s Hcap') // e.g. 4目置碁 → 4s Hcap
              .replace(/(\d+)目半出し/g, '$1.5 komi') // e.g. 6目半出し → 6.5 komi
              .replace(/(\d+)目出し/g, '$1 komi') // e.g. 6目出し → 6 komi
              .replace(/(\d+)目/g, '$1s') // e.g. 3目 → 3s
              .replace(/(\d+)子/g, '$1s') // e.g. 4子 → 4s
              // Even / fixed colour
              .replace(/互先/g, 'Even')
              .replace(/定先/g, 'Fixed')
              // Komi / other
              .replace(/コミない/g, 'No komi')
              .replace(/置碁/g, 'Hcap')
              // Clean up leftover Japanese punctuation
              .replace(/　/g, ' ') // full-width space
              .trim();
          }
          return r;
        });
      }
      return JSON.stringify(data);
    } catch (e) {
      return text;
    }
  }

  // ── G_VAR server name patcher (polls until config.js has executed) ────────
  function patchServerNames() {
    if (typeof G_VAR !== 'undefined' && G_VAR.SERVER_JP) {
      G_VAR.SERVER_JP = G_VAR.SERVER_JP.map(function (s) {
        return [s[0], SERVER_NAMES[s[1]] || s[1], s[2], s[3], s[4], s[5], s[6]];
      });
      console.log('[toyo-translate] SERVER_JP patched');
    } else {
      setTimeout(patchServerNames, 50);
    }
  }

  patchServerNames();

  // ── fetch() interception (gibo_load uses fetch, not XHR) ─────────────────
  const origFetch = window.fetch;
  window.fetch = function (input, init) {
    const url = typeof input === 'string' ? input
              : (input && input.url) ? input.url
              : '';

    if (!url.includes('gibo_load')) {
      return origFetch.apply(this, arguments);
    }

    return origFetch.apply(this, arguments).then(function (response) {
      return response.text().then(function (text) {
        const patched = patchGibo(text);
        console.log('[toyo-translate] gibo patched successfully');
        return new Response(patched, {
          status:     response.status,
          statusText: response.statusText,
          headers:    response.headers,
        });
      });
    });
  };

  // ── XHR interception (for lang.xml) ──────────────────────────────────────

  const NativeOpen = XMLHttpRequest.prototype.open;
  const NativeSend = XMLHttpRequest.prototype.send;

  XMLHttpRequest.prototype.open = function (method, url) {
    this._toyoPatch = (typeof url === 'string' && url.includes('lang.xml'))
      ? 'lang'
      : null;
    return NativeOpen.apply(this, arguments);
  };

  XMLHttpRequest.prototype.send = function () {
    if (!this._toyoPatch) {
      return NativeSend.apply(this, arguments);
    }

    const xhr = this;
    let appHandler = null;
    let patched = false;

    function applyPatch() {
      if (patched) return;
      patched = true;
      try {
        const rawText = Object.getOwnPropertyDescriptor(
          XMLHttpRequest.prototype, 'responseText'
        ).get.call(xhr);

        const patchedText = patchLangXml(rawText);

        Object.defineProperty(xhr, 'responseText', {
          value: patchedText, writable: false, configurable: true
        });
        Object.defineProperty(xhr, 'response', {
          value: patchedText, writable: false, configurable: true
        });

        const parser = new DOMParser();
        const xmlDoc = parser.parseFromString(patchedText, 'application/xml');
        Object.defineProperty(xhr, 'responseXML', {
          value: xmlDoc, writable: false, configurable: true
        });

        console.log('[toyo-translate] lang.xml patched successfully');
      } catch (e) {
        console.warn('[toyo-translate] patch error:', e);
      }
    }

    Object.defineProperty(xhr, 'onreadystatechange', {
      set: function (fn) { appHandler = fn; },
      get: function (){ return appHandler; },
      configurable: true
    });

    xhr.addEventListener('readystatechange', function () {
      if (xhr.readyState === 4) {
        applyPatch();
        if (appHandler) {
          try { appHandler.call(xhr); } catch (e) {}
        }
      }
    }, true);

    return NativeSend.apply(this, arguments);
  };

})();